### ISSUE TITLE
Feature Request: Allow multiple arrows in shortcuts

### ISSUE THREAD

**Issue by d3v1an7** [eczarny/spectacle#629] opened 2016-08-01 02:14 UTC
I can never seem to remember the upper/lower left/right keyboard combinations (just me? 😄 )

I'd love to combine arrows to simplify the combination, for example:
**Upper Left:** ⌥⌘←↑
**Lower Left:** ⌥⌘←↓
**Upper Right:** ⌥⌘→↑
**Lower Right:** ⌥⌘→↓

When attempting this, I get a dialogue with the error:
```
Shortcut ⌥⌘← already in use.
The shortcut "⌥⌘←" is already in use. Please select a new shortcut.
```

Thank you to all contributors on this project! ❤️

**Comment by eczarny** [comment] 2016-08-27 02:11
Duplicate of #105.

**Closed by eczarny** 2016-08-27 02:11 UTC
