### ISSUE TITLE
Windows are automatically switched back when changing to other display

### ISSUE THREAD

**Issue by liub3** [eczarny/spectacle#583] opened 2016-05-03 23:19 UTC
I connected my 13 MBP to an external monitor and the external monitor is larger than my MBP's display. What I usually do is switching windows between displays. The problem is:
When I switch window(window size just fit MBP) from MBP to external monitor everything is fine.
When I switch window(window size larger than MBP display) from external monitor to MBP then window will be automatically switched back.
So 
smaller window to larger display (OK)
larger window to smaller display (Switched back to larger display)

This problem has never happened before so just in latest update(1.0.5 [590]).

FYI: in previous version when larger window is switched to smaller display then the window will be resized to fit the smaller display.

**Comment by eczarny** [comment] 2016-05-03 23:20
Closing as a duplicate of #575.

**Closed by eczarny** 2016-05-03 23:20 UTC
