### ISSUE TITLE
[Feature Request] - Padding for arranged windows.

### ISSUE THREAD

**Issue by maus-** [eczarny/spectacle#413] opened 2015-06-30 21:24 UTC
Sometimes I prefer to have a small bit of width between each window, it would be awesome if that could be a setting with variable width/height.

**Comment by nii236** [comment] 2015-07-02 03:59
This will be really awesome. We will finally be able to go toe to toe with the tiling window manager beasts like BSWPM and [i3 (with gaps)](http://devthe.com/files/i3demo.webm)!

**Comment by naggie** [comment] 2015-07-10 14:52
Agreed, very useful. I don't necessarily use a tiled WM for space efficiency alone, more so to reduce time spent reszing/moving with the mouse. Gaps allow me to see 5% my marvellous desktop background of a forest. That 5% is important!

**Comment by s3ththompson** [comment] 2015-08-13 21:21
Big +1

**Comment by eczarny** [comment] 2015-08-13 23:49
Duplicate of #67.

**Closed by eczarny** 2015-08-13 23:49 UTC
Labels: enhancement, ★★
