### ISSUE TITLE
Feature Request:  Move window to another space/desktop using only keyboard

### ISSUE THREAD

**Issue by lukedegruchy** [eczarny/spectacle#729] opened 2017-02-15 02:54 UTC
This is a feature request to enable moving windows between spaces/desktops using only the keyboard.  Currently, the only way I know of to do this is to open Mission Control and drag the window in question to the other space or to click and hold on the Window and then use the keyboard shortcuts to move between spaces (ex CTRL-Right).

So, for example, with the window selected, SHIFT-CTRL-Right would move the window to the space immediately to the right without using the mouse or trackpad.

**Comment by modkaffes** [comment] 2017-02-17 10:09
Frequently requested but a duplicate of #15

**Closed** 2017-02-25 20:52 UTC
