### ISSUE TITLE
Menu bar icon

### ISSUE THREAD

**Issue by p-s-** [eczarny/spectacle#300] opened 2014-12-11 12:47 UTC
Spectacle is a wonderful application, has a fantastic app icon,
but the menu bar icon looks kind of meh ..

I just filled the glasses in pixelmator, and it looks much better (for me)
I can't upload the tiff here, so I converted it to png; but maybe someone with better image editing skills can do a better job ..
(It doesn't look that clear anymore. Maybe I didn't use the right parameters to save?)

(Or is this a stupid request anyway? In this case I'm sorry for wasting Your time!)

![spectacle status item](https://cloud.githubusercontent.com/assets/9105301/5394277/ca55d21a-813b-11e4-8b4b-48c0c8039cef.png)

**Comment by eczarny** [comment] 2015-04-10 18:04
Closing as a duplicate of #238.

**Closed by eczarny** 2015-04-10 18:04 UTC
