### ISSUE TITLE
Stop working after sometime with Webstorm and Rubymine IDE from JetBrain

### ISSUE THREAD

**Issue by sainiAman** [eczarny/spectacle#526] opened 2016-02-04 17:10 UTC
When you open Webstorm or Rubymine is works fine but after sometimes it stop working with only those.

**Comment by jmaciasluque** [comment] 2016-02-05 16:09
:+1: IntelliJ 

This is pretty annoying.

**Comment by tells** [comment] 2016-02-06 21:32
I have to restart webstorm to have spectacle work again.

**Comment by mpalmujoki** [comment] 2016-02-09 08:55
It's sufficient that you swap a couple times between files to reproduce it. Really annoying

**Comment by eczarny** [comment] 2016-02-10 21:18
I believe this is an issue with these IDEs recently moving to a recent JVM. Here is the issue being tracked by JetBrains:

https://youtrack.jetbrains.com/issue/IDEA-149718

Closing this as a duplicate of #500.

**Closed by eczarny** 2016-02-10 21:18 UTC
