### ISSUE TITLE
Weird behaviour since El Captian [GIF]

### ISSUE THREAD

**Issue by mvaneijgen** [eczarny/spectacle#481] opened 2015-10-14 08:50 UTC
This is what happens to safari when going fullscreen. Its very slow with resizing and it doesn't what it always did. 

![Spectacle](http://i.imgur.com/BmW7u5Z.gif)

The weird thing is that the Finder still works like it always has.

**Comment by eczarny** [comment] 2015-10-15 02:58
Duplicate of #446.

**Closed by eczarny** 2015-10-15 02:58 UTC
