### ISSUE TITLE
Feature suggestion: Move windows through osx spaces (maybe repost-sorry about it)

### ISSUE THREAD

**Issue by LucaMarzialetti** [eczarny/spectacle#605] opened 2016-05-25 15:28 UTC
I would really like the feature of space move neither than monitor movement 
This app would be perfect with it!

**Comment by denysdovhan** [comment] 2016-06-02 16:28
+1
I would like to have this to.

**Comment by pheuberger** [comment] 2016-07-01 09:26
This would be really helpful!

**Comment by eczarny** [comment] 2016-07-15 04:05
Duplicate of #15.

**Closed by eczarny** 2016-07-15 04:05 UTC
