### ISSUE TITLE
Next/Prev Screens not in order with 3 external monitors - Macbook pro

### ISSUE THREAD

**Issue by df-andrews** [eczarny/spectacle#306] opened 2015-01-14 16:42 UTC
Thanks for the great app, Spectacle has been amazing helpful! 

On my late 2013 Macbook Pro, I have 3 external monitors. One to the left of my Macbook and 2 to the right. When using the Prev/Next monitor functions, it doesnt go in order.

A window on the far left, will go from its screen (monitor 1) and goes direct to monitor 3, than monitor 4 and lastly monitor 2.

**Comment by trevordunn** [comment] 2015-03-02 17:22
This is a duplicate of https://github.com/eczarny/spectacle/issues/298

**Comment by eczarny** [comment] 2015-04-10 17:50
Closing as a duplicate of #298.

**Closed by eczarny** 2015-04-10 17:50 UTC
