### ISSUE TITLE
After waking Mac from sleep, some windows don't position correctly anymore

### ISSUE THREAD

**Issue by marlonrichert** [eczarny/spectacle#736] opened 2017-03-03 08:08 UTC
The window will appear in a different position then it was before my Mac went to sleep. Using Spectacle to reposition it produces weird results, which large parts of the window going outside the screen. Restarting Spectal does not help, but restarting the application with the bad window fixes it.

I'm using an external thunderbolt display in addition to my MacBook Pro's built-in screen. This does not happen every time I wake it from sleep, but often enough to be a nuisance. Also, it can happen to more than one app after sleep.

**Comment by jdd08** [comment] 2017-03-09 17:50
I get the same issue but restarting the app in question doesn't fix it - the commands still work but there is a 5-10 second lag for them to take effect

**Comment by ActionScripted** [comment] 2017-03-29 20:37
For me what happens is when my computer wakes from sleep my primary monitor does not turn back on. Closing Spectacle resolves this issue.

I wasn't sure at first what might be causing the problem. The latest OS X update includes NightShift and other display-related changes so I figured it was OS-related. Reset the SMC, reset NV/PRAM, tried safe mode, downloaded OS X update bundle and reinstalled the update.

Maybe Spectacle isn't the issue. Maybe it's just some weird coincidence. Happy to help with logs, troubleshooting or anything else that might narrow down the problem.

Details:
- Spectacle Version 1.2 (672)
- OS X 10.12.4
- iMac (Retina 5K, 27-inch, Late 2015)

**Comment by eczarny** [comment] 2017-05-24 20:00
@marlonrichert I'm not sure I follow. Are you unplugging the external display by any chance? That likely throws things off a bit.

**Comment by marlonrichert** [comment] 2017-05-25 09:52
@eczarny, nope, I keep it plugged in.

**Comment by eczarny** [comment] 2017-05-25 13:32
@marlonrichert how are you using Spectacle to reposition windows? I'd like to better understand what's going on. What are the exact steps to reproduce the issue? Going into more detail here would help me a lot. A video recording of the problem would be even better (you can use QuickTime Player to make a screen recording).

**Comment by marlonrichert** [comment] 2017-05-25 14:35
Sorry, I don't have an display anymore. :(

**Comment by eczarny** [comment] 2017-05-26 14:27
Closing since this isn't actionable. Feel free to reopen if you encounter the issue again!

**Closed by eczarny** 2017-05-26 14:27 UTC
Labels: investigating
