### ISSUE TITLE
Windows moved from one display to another move themselves back

### ISSUE THREAD

**Issue by dfevre** [eczarny/spectacle#567] opened 2016-05-02 00:35 UTC
When using ctrl+option+command+-> to move a window from one display to another it will pop back to where is was after w few seconds. I only started noticing this after the 1.0.4 update.

Version 1.0.4 now seems to change the window size when moving between displays of different sizes. Some apps seem to not like being reduced down below a certain size so they go back to the other display. 

I'm running OS X 10.11.4 on a Macbook Pro 13" with Spectacle 1.0.4. Switching between displays seems to work fine for Google Chrome but Slack and Outlook display the problem I've described.

**Comment by eczarny** [comment] 2016-05-02 03:32
The intended behavior in 1.0.4 is to try and keep windows in a relatively similar position when being moved to another display. As a result the size of windows can change to accommodate the size of the new display. In the scenario you describe Spectacle fails to do so for apps that restrict their dimensions. The window can't fit in the new location in the destination display so Spectacle puts it back.

As a workaround you have a couple of options:

1. Resize the window to better fit the destination display before moving it to that display
2. Open the application bundle and modify https://github.com/eczarny/spectacle/blob/master/Spectacle/Resources/Window%20Position%20Calculations/SpectacleNextOrPreviousDisplay.js#L16 to return `visibleFrameOfDestinationScreen`; you should find `SpectacleNextOrPreviousDisplay.js` under `Contents/Resources/Window Position Calculations`

**Comment by eczarny** [comment] 2016-05-02 03:42
Better yet, to revert back to the previous behavior you can copy the calculation used here to center windows:

https://github.com/eczarny/spectacle/blob/master/Spectacle/Resources/Window%20Position%20Calculations/SpectacleCenterWindowCalculation.js

Replace the body of `moveWindowRectToDisplay` with the body window calculation used to center windows.

**Comment by krstffr** [comment] 2016-05-02 07:00
This actually breaks the app for me, as I frequently move many app windows around my three screens when starting my computer, and no matter what size I change the app windows to they still won't move between screens (even though screen sizes are quite similar). The move-apps-between-screens-at-startup are probably 80% of what I use Spectacle for.

I can't imagine this is the new intended behaviour as it was working just fine before?

**Comment by justincoh** [comment] 2016-05-02 13:57
Was having the same issue here, but it magically resolved itself about 5 minutes after boot. I did exactly nothing, not even a restart. I don't know if this helps, but:
```
Spectacle - 1.0.4
MacBook Pro - OSX 10.11.4
```
Good luck, and thanks for spectacle

**Comment by eczarny** [comment] 2016-05-02 14:24
I'm planning to replace the current behavior with a less complicated alternative.

**Comment by krstffr** [comment] 2016-05-02 14:25
@eczarny that's great! 👍

**Comment by eczarny** [comment] 2016-05-02 18:42
And by "less complicated alternative" I mean the previous 1.0.3 behavior.

**Comment by eczarny** [comment] 2016-05-02 23:44
I just released 1.0.5 with the fix for this issue. Once I receive some confirmation from folks that this is working again I'll go ahead and close this out.

**Comment by dfevre** [comment] 2016-05-03 00:11
Thanks for that. I've just updated to 1.0.5 and it's working well for me.

**Closed** 2016-05-03 01:31 UTC
Labels: defect, pending-release, ★★★

**Comment by krstffr** [comment] 2016-05-03 07:13
Maybe this is a discussion to be held elsewhere, but if I want to move my "big" Chrome window from my big screen onto my smaller screen (which would not fit the window unless it resized it), my prefered behaviour would be for the Chrome window to get moved to the new window and resize instead of first having to manually resize it before the move. **Avoiding manual resizing/moving is kind of the whole point for Spectacle (in my opinion).**

This is not the case even after the bug fix (thanks for that by the way, now I can move most windows!)

Keep up the good work!
