### ISSUE TITLE
Resize windows with "repeated shortcut" handling

### ISSUE THREAD

**Issue by sandreas** [eczarny/spectacle#623] opened 2016-07-16 14:07 UTC
Hey,

for my use case it would be very useful, if spectacle would not react at a "per single shortcut"-Base, but detects "repeated shortcuts". 

For instance:
While Alt+CMD+Left resizes current window to the left half of the screen and Alt+CMD+Bottom resizes it to the bottom half of the screen, a combination of these two (Alt+CMD, then Left, then Bottom) could fit it to the left bottom quarter of the screen instead of first resizing to the left half, then resizing it to the bottom half.

Repeating this shortcut could make the window smaller and smaller (always the half of the current window size).

What do you think?

**Comment by eczarny** [comment] 2016-07-24 18:18
@sandreas is what you're describing similar to #599?

**Comment by sandreas** [comment] 2016-07-24 18:25
yes sorry, didn't read :-) Thank you.

**Comment by eczarny** [comment] 2016-07-24 18:29
Closing as a duplicate of #599.

**Closed by eczarny** 2016-07-24 18:29 UTC
