### ISSUE TITLE
Sizing a window to the top half moves the window down slightly

### ISSUE THREAD

**Issue by azdavis** [eczarny/spectacle#323] opened 2015-02-11 21:57 UTC
Spectacle 0.8.8, OS X 10.10.2 (14C109)

When a window is fullscreen'd, the window resize arrow points in only one direction:

![fullscreen](https://cloud.githubusercontent.com/assets/6496454/6157304/4a82feec-b20e-11e4-8c26-bf48974d2a98.png)

![fullscreen1](https://cloud.githubusercontent.com/assets/6496454/6157361/b26e2fe0-b20e-11e4-859a-f18932a191f5.png)

But when the window is put to the top half of the screen, it moves down slightly:

![top half](https://cloud.githubusercontent.com/assets/6496454/6157310/558fcc16-b20e-11e4-8a2f-78e347f328f7.png)

![top half1](https://cloud.githubusercontent.com/assets/6496454/6157359/ad195362-b20e-11e4-8c65-0747b56f60c2.png)

**Comment by rogierstuyver** [comment] 2015-02-14 17:21
Related to #321.

**Comment by eczarny** [comment] 2015-04-10 17:23
Closing as a duplicate of #321. This issue has been bothering me and I'm keen to get a fix in.

**Closed by eczarny** 2015-04-10 17:23 UTC
