### ISSUE TITLE
"Multi step" hotkey trigger support

### ISSUE THREAD

**Issue by emattias** [eczarny/spectacle#429] opened 2015-08-16 17:40 UTC
I often arrange my windows in top left/right and bottom left/right quarters and I have never found a good intuitive keyboard shortcut for this.

I would like to have a keyboard shortcut where if I just press CMD + ALT + CTRL + UP it will resize and position the active window to take up the top half of the screen, but if I immediately (within a time limit, maybe 1 sec) press LEFT or RIGHT, after the CMD + ALT + CTRL + UP trigger it will be positioned in the top left/right quarter instead of the whole top half of the screen.

**Comment by eczarny** [comment] 2015-08-17 21:53
Duplicate of #105.

**Closed by eczarny** 2015-08-17 21:53 UTC
