### ISSUE TITLE
Hot key in use, but actually not

### ISSUE THREAD

**Issue by waynehoover** [eczarny/spectacle#322] opened 2015-02-10 01:07 UTC
I'm trying to bind  "⌃⌘Space" but I get the error that the hot key is in use and that I should change the existing shortcut in the Keyboard preference pane under System Preferences. The only issue is that there isn't anything assigned to  "⌃⌘Space" (I disabled everything) so why won't it let me bind to it?

**Comment by janniklorenz** [comment] 2015-02-12 11:56
Duplicate of #319.

**Comment by eczarny** [comment] 2015-04-10 17:26
Closing as a duplicate of #319.

**Closed by eczarny** 2015-04-10 17:26 UTC

**Comment by eczarny** [comment] 2015-04-10 17:29
⌃⌘Space is actually assigned to "Edit" -> "Special Characters..." in the menu bar. Spectacle relies on its own standard (though hidden) menu bar so that it knows it should not allow these commonly claimed shortcuts to be used.

**Comment by waynehoover** [comment] 2015-04-10 21:26
Yes but I have rebound the special characters option to another key
combination already in the keyboard prefs.
