### ISSUE TITLE
Update Not Working Well

### ISSUE THREAD

**Issue by FrankDraws** [eczarny/spectacle#365] opened 2015-04-17 20:58 UTC
I have a 15" MacBook Pro pushing a Thunderbolt and Cinema Display. 

For some reason it no longer works with the Terminal window. When I hit the shortcut to move it to the middle monitor (i.e. Cinema Display), it jumps back to the main monitor on the left (Thunderbolt).

**Comment by cyphercommunications** [comment] 2015-04-17 21:16
+1

**Comment by eczarny** [comment] 2015-04-17 21:18
Closing as a duplicate of #363.

**Closed by eczarny** 2015-04-17 21:18 UTC
