### ISSUE TITLE
Trying to left/right position window forces to left side?

### ISSUE THREAD

**Issue by ckcollab** [eczarny/spectacle#381] opened 2015-04-27 20:14 UTC
Whenever I try to send my terminal to the left OR right half of the screen, it gets weirdly positioned like this? This wasn't happening until recently, maybe I broke something locally? I looked at some other issues at no one seems to have this _exact problem_ so it could be me.

![image](https://cloud.githubusercontent.com/assets/2185159/7356783/41f1075e-ecdf-11e4-88e0-a0759c5e9aaf.png)

NOTE: Some other windows seem to work fine?

**Comment by eczarny** [comment] 2015-04-27 21:15
What version of Spectacle are you using?

**Comment by ckcollab** [comment] 2015-04-27 21:47
0.8.9 -- I also got the problem in 0.8.10 but downgraded to see if it was fixed, it wasn't.

I also tried closing/reopening the windows to see if that would fix it, didn't seem to. It's strange some windows work and the Terminal doesn't!?

**Comment by ckcollab** [comment] 2015-04-28 18:49
Also, when I don't have multiple monitors attached everything works fine.

**Comment by eczarny** [comment] 2015-08-11 21:04
Closing as a duplicate of #371.

**Closed by eczarny** 2015-08-11 21:04 UTC
Labels: investigating

**Comment by ckcollab** [comment] 2015-08-31 18:12
Confirmed that this is fixed in latest version....... THANKS!!
