### ISSUE TITLE
"Next Display" Direction not consistent

### ISSUE THREAD

**Issue by Arkinator** [eczarny/spectacle#739] opened 2017-03-08 09:23 UTC
I have two different three Monitor setups that i am using with my MacBook Pro. But when I cycle the windows through the screens (Next Display/Previous Display) the order is reversed for both setups. This even persists with a bit of screen switching, but that just might be coincidence (given its 50/50...).
I am not sure what additional information I can provide here, so just ping me if you wanna know something.

**Comment by BenBergman** [comment] 2017-04-24 13:51
I am experiencing similar behaviour. I think the issue is that the displays are numbered by OS X in a way that is totally distinct from display order, so "Next display" is just moving to the next number and not the adjacent display. Changing to work with display positioning rather than numbering might solve this, but it could get weird for people with display arrangements that aren't just a straight line (eg. a grid).

**Comment by eczarny** [comment] 2017-05-24 19:54
Closing as a duplicate of #298.

**Closed by eczarny** 2017-05-24 19:54 UTC
