### ISSUE TITLE
Move window between desktops/spaces [enhancement]

### ISSUE THREAD

**Issue by Trinition** [eczarny/spectacle#591] opened 2016-05-05 12:18 UTC
Moving between multiple physical displays is nice, but if you use multiple virtual Desktops / Spaces, you also want to be able to move windows between them (like in SizeUp).

**Comment by eczarny** [comment] 2016-05-05 16:51
Likely not something Spectacle will be supporting for a while, unfortunately. Closing as a duplicate of #15.

**Closed by eczarny** 2016-05-05 16:51 UTC
