### ISSUE TITLE
Next Display wrong direction when primary monitor changed

### ISSUE THREAD

**Issue by unclhos** [eczarny/spectacle#566] opened 2016-04-26 20:14 UTC
When you change the "primary monitor" (white bar on arrangement displays) to an external monitor, the direction of "next/previous" monitor is incorrect. 

Spectacle 1.0.3
OSX 10.11.4

**Comment by eczarny** [comment] 2016-04-27 00:50
Closing as a duplicate of #298.

**Closed by eczarny** 2016-04-27 00:50 UTC

**Comment by unclhos** [comment] 2016-04-27 01:10
I think this is different. On my system it works correctly when primary is set to my MBP. But incorrectly when I change "primary" to one of the externals. But up to you.
