### ISSUE TITLE
Cannot assign ⌃⌥⌘↑

### ISSUE THREAD

**Issue by marlonrichert** [eczarny/spectacle#676] opened 2016-11-04 11:39 UTC
I want to assign Top Half to ctrl-alt-cmd-up, but for some reason, Spectacle doesn't accept that. I get to see ⌃⌥⌘ in the input field when I hold the ctrl, option and cmd keys, but when I then press arrow up, nothing happens.

**Comment by sergej-koscejev** [comment] 2016-11-14 10:49
This happens to me with another app (Magnet), only in my case it is the other way around: Spectacle accepts ctrl-alt-cmd-up but Magnet doesn't. I would also like to know the reason for this.

**Comment by eczarny** [comment] 2016-12-01 16:36
Is there any relevant output from Console? This works as expected for me but I'd like to know a bit more about what may be going on.

**Comment by eczarny** [comment] 2016-12-01 16:52
Duplicate of #652.

**Closed by eczarny** 2016-12-01 16:52 UTC
Labels: investigating

**Comment by marlonrichert** [comment] 2016-12-08 13:19
@eczarny, I tried, but it does not seem to produce any output in Console.
