### ISSUE TITLE
Terminal and iTerm do not shrink to 1/3 size vertically

### ISSUE THREAD

**Issue by selfup** [eczarny/spectacle#531] opened 2016-02-13 06:53 UTC
* Used to be able to shrink the terminal to 1/3 or 2/3 size. 
* Now the terminal and iterm apps do not size correctly.

**Comment by madbeagle** [comment] 2016-02-13 13:59
Having this issue as well right after the update.

**Comment by RobertAKARobin** [comment] 2016-02-13 17:50
+1

**Comment by RobertAKARobin** [comment] 2016-02-13 18:03
[Download link for 1.0.1](https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.0.zip) which works fine with Terminal. However, the Finder does not resize to 1/3.

**Comment by selfup** [comment] 2016-02-13 18:31
@RobertAKARobin Thank you so much for that link!

**Comment by RyanS** [comment] 2016-02-13 19:23
Just want to say I got the same thing. Was used to having iTerm take up 1/3 and then mac vim take up the next 2/3rds. It appears that is no longer possible with the new update

**Comment by eczarny** [comment] 2016-02-13 21:06
I think d3c0a8a9325ba942aafb7d7c6f7812b7d36cd787 may fix the issue. It does for me in my testing with Terminal. If folks are able to build and run Spectacle could they try out this fix on master and report back?

**Comment by dacodekid** [comment] 2016-02-14 14:05
@eczarny  I tried but `pod install` fails with below.

```
╰─$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

――― MARKDOWN TEMPLATE 

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b25128f4299b98d7461733de5af85aefa6642952
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.9'

pod 'Sparkle', '~> 1.13.1'

target :SpectacleSpecs, :exclusive => true do
  pod 'Specta', '~> 1.0.5'
  pod 'Expecta', '~> 1.0.5'
  pod 'OCMockito', '~> 3.0.1'
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Sparkle">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END 

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22Sparkle%22%3E%0ADid+you+mean%3F++to_query&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
```

**Comment by eczarny** [comment] 2016-02-14 22:29
@dacodekid does CocoaPods behave correctly when using the default version of Ruby?

**Comment by selfup** [comment] 2016-02-15 16:08
@dacodekid are you using rvm, rbenv, or chruby? Or is this an update you made to the system ruby?

Thanks for taking the time to run a test build!

**Comment by dacodekid** [comment] 2016-02-15 16:16
@eczarny - I don't have any experience with CocoaPods.  Just followed the steps from `readme` though.

@selfup - I ran this with brew version `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

**Comment by eczarny** [comment] 2016-02-15 20:10
@dacodekid If you `brew unlink ruby` and try `pod install` do you see the same error?

**Comment by selfup** [comment] 2016-02-15 22:00
@dacodekid the `brew unlink ruby` will bring you back to system ruby and it should work!

Then you can go back and `brew link ruby` to have 2.3.0 back

I suggest checking out rbenv to manage your rubies!

**Comment by dacodekid** [comment] 2016-02-15 22:36
@eczarny / @selfup  -  just `brew unlink` didn't work for me. I had to 

* completely uninstall both 'ruby & cocopods' 
*reinstall cocopods
* re-download the source
* `pod install` worked fine. 

However, the problem still exists. My current workaround for 1/3 is `ctl + opt`.

**Comment by Rastalamm** [comment] 2016-02-16 02:01
+1 for this.. 

@dacodekid -- your 'hack' for the 1/3 is good enough for now until this bug gets fixed. 

Thanks!

**Comment by selfup** [comment] 2016-02-16 16:04
@Rastalamm Does ```ctl + opt``` behave differently?

If so, show me light!

**Comment by Rastalamm** [comment] 2016-02-16 17:24
@selfup `ctl + opt` will automatically make the window into 1/3 of the screen. 

So instead of doing `cmd + opt` and hitting the L/R arrows a few times to get to 1/3, you can do `ctl opt` and the arrow keys to where you want (left, center right, top, bottom, middle)

**Comment by selfup** [comment] 2016-02-16 17:31
@Rastalamm Interesting! Thanks. Only work left and right for me. No worries though. I will wait for the fix to this bug.

**Comment by Rastalamm** [comment] 2016-02-16 17:33
@selfup - I just tried playing with it and it didn't work for every window I had open. 

Works on iTerm, sublime and chrome but not on Airmail 2

**Comment by sterling** [comment] 2016-02-16 18:34
+1 Toggling through quarters (1/4, 1/2, 3/4) has not been working since last update for iterm/terminal

**Comment by zhimsel** [comment] 2016-02-16 18:48
@eczarny FYI, I built Spectacle at b0997e5 (which includes d3c0a8a93, as you mentioned above). Still happening there. I'm running OSX 10.10.5 and iTerm2. I didn't test Terminal.

**Comment by RobertAKARobin** [comment] 2016-02-16 18:53
@selfup Oops, I made a typo in the link. Here we go:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.1.zip

**Comment by zhimsel** [comment] 2016-02-16 18:59
@eczarny Did some iterative testing and it seems (for me at least), that this issue was introduced in 512624b; it works fine in 06a38c8. Hopefully that helps narrow down where the bug is in code.

**Comment by selfup** [comment] 2016-02-16 22:22
@RobertAKARobin Thank you so much!

![](http://www.reactiongifs.com/r/omgshoop.gif)

**Comment by eczarny** [comment] 2016-02-16 22:27
@zhimsel If you undo my change in d3c0a8a9325ba942aafb7d7c6f7812b7d36cd787 do you see the issue being fixed on master? I have a feeling that cb80a9267349c2eeb1cd4c566e366330ff034d84 may have fixed the root cause.

**Comment by zhimsel** [comment] 2016-02-16 22:36
@eczarny It does (fix that issue). Here's what I did:

1. `git checkout b0997e5`
1. `git revert d3c0a8a`
1. `pod install && open Spectacle.xcworkspace`
1. Built and ran

Works fine in iTerm2. Confirmed that it's broken on b0997e5, but if you revert d3c0a8a and build, it works.

**Comment by eczarny** [comment] 2016-02-17 01:02
Reverted. Thanks for the help @zhimsel!

**Comment by zhimsel** [comment] 2016-02-17 01:03
:+1:

**Comment by eczarny** [comment] 2016-02-17 02:18
I would love some additional help testing the fix. I created a beta release that should resolve the issue, you can download it here:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.3b.zip

**Comment by dacodekid** [comment] 2016-02-17 04:32
@eczarny opened an issue here https://github.com/eczarny/spectacle/issues/538 for 1.0.3b

**Comment by selfup** [comment] 2016-02-17 17:30
@eczarny Thanks for the hard work! I will test out 1.0.3b

**Comment by zhimsel** [comment] 2016-02-17 18:02
@eczarny `1.0.3b` is working fine for me so far (regarding the Terminal 1/3 resizing issue). No other issues noticed yet.

**Comment by zhimsel** [comment] 2016-02-17 18:26
@eczarny Scratch that. I'm having the same (or similar) issue as @dacodekid is with multiple monitors. I have two monitors, vertically (Built-in Retina under external LCD screen). The "next display" command only pushes it from external -> retina, not the other way around.

**Comment by eczarny** [comment] 2016-02-17 21:44
Good find @zhimsel! I just reproduced your issue. I'll take a look tomorrow.

**Comment by dacodekid** [comment] 2016-02-18 03:52
I disconnected couple monitors and tried to produce @zhimsel's issue, but couldn't.

**Comment by caius** [comment] 2016-02-18 16:16
Just came along to see if anyone else had reported this issue with Terminal.app, tested 1.0.3b and it works for me too. :+1:

**Comment by zhimsel** [comment] 2016-02-18 18:41
@dacodekid @eczarny confirmed that the screen switching is still broken for me in 1.0.3b (thought it might be a fluke). More info in #538

**Comment by NodeGuy** [comment] 2016-02-19 04:38
The beta release fixed the problem for me, thank you.

**Comment by cosenal** [comment] 2016-02-21 10:46
Same here, the beta release fixes the issue. :+1:

**Closed** 2016-02-21 20:41 UTC

**Comment by RobertAKARobin** [comment] 2016-02-24 01:17
Thank you for fixing!

**Comment by zhimsel** [comment] 2016-02-24 01:32
Indeed! 1.0.3 fixes both issues :) Thanks!


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net

**Comment by selfup** [comment] 2016-02-24 16:57
This was a nice experience as well as a quick turnaround.

Awesome!

**Comment by eczarny** [comment] 2016-02-24 20:43
:+1:
