### ISSUE TITLE
Spectacle 1.0.3b Issues on multi monitors

### ISSUE THREAD

**Issue by dacodekid** [eczarny/spectacle#538] opened 2016-02-17 04:29 UTC
This version some what fixed the 1/3 issue on iTerm2/Terminal issue, but introducing few other "random" issues on multi monitors (some I couldn't reproduce - some 'suddenly start working fine, but then close/repoen the window and it's back). This is my current setup:

Three monitors on portrait mode *(I1 I2 I3)* and mac screen *(-4)* - positioned as 1234.  Testing just iTerm2.

(Note: Even prior <=1.0.1, Spectacle always moves my screen as 1 -> 2 -> 4 -> 3)

### MOVING SCREENS `ctl+opt+cmd`  From Left to Right - 
**Open iTerm2 on Monitor 1**
1 -> 2 -> 4 -> 2 -> 4 -> 2 -> 4 -> 2 -> 4 -> 2 (never gets 3, stuck in 2<->4 loop)

**Close / Reopen iTerm2 on Monitor 2**
2 -> 4 (stuck). 

**Close / Reopen iTerm2 on Monitor 3**
3 -> 1 -> 2 -> 4  -> 1 -> 2 -> 4  (Skips 3) 

**Close / Reopen iTerm2 on Monitor 4**
4-> 3 -> 1 -> 2 -> 4-> 3 -> 1 -> 2 -> (Works as 'expected') 

### MOVING SCREENS `ctl+opt+cmd`  From Right to Left - 
**Close / Reopen iTerm2 on Monitor 1**
1 <- 3 <- 4 <- 3  <- 4  (Skips 2. Stuck in 3 <-> 4 loop) 

**Close / Reopen iTerm2 on Monitor 2**
2 <- 1 <- 3 <- 4 <- 1 <- 3 <- 4    (Skips 2) 

**Close / Reopen iTerm2 on Monitor 3**
3 <- 4 (stuck)

**Close / Reopen iTerm2 on Monitor 4**
4 <- 2 <- 1 <- 3 <- 4 <- 2 <- 1 <- 3 (Works as 'expected').

--
The reason I'm closing & reopening iTerm2 is, if I 
- open iTerm2
- switch between apps (Chrome)
- move 

Then works exactly as above. But if I
- open iTerm2
- move to next screen
- switch between apps (Chrome)

Now it behaves (and produces as above) as iTerm2 is opened from that moved window. 

For Example, 
- Open iTerm2 on Monitor 1
- Move to 2 ( 1 -> 2)
- Switch iTerm2 -> Chrome -> iTerm2
- 2 -> 4 (stuck - as it opened from Monitor 2 from above test)

--

Now I'm moving iTerm2 on both directions (random)
**Open iTerm2 on Monitor 1**
1 -> 2 -> 4 -> 2 -> 4 -> 2 -> 4 <- **3** <- 4 <- 3 -> 1 -> 2 <- 1 <- 3 <- 4 <- 3 <- 4 

 Hope you get the pattern.

**Comment by eczarny** [comment] 2016-02-17 04:34
Do you see this behavior with other apps? How about Terminal (another app with quantized windows)?

**Comment by eczarny** [comment] 2016-02-17 04:40
Tracking down this issue will be a bit difficult; I only have access to at most two displays. @dacodekid if you're feeling up to it you could try debugging `SpectacleScreenDetector` with your setup. The next time I have access to multiple displays I'll try and see if I can find anything obviously wrong.

**Comment by dacodekid** [comment] 2016-02-17 04:44
@eczarny - I just tested (and still testing all possibilities) with Terminal & Chrome and they all behaves the same. Unfortunately I know nothing about `Objective C` or in any terms of `mac apps` but certainly willing to do manual tests.

**Comment by eczarny** [comment] 2016-02-17 04:48
Thanks @dacodekid! I'll dive into this a bit more tomorrow.

**Comment by eczarny** [comment] 2016-02-17 05:00
I may have an idea what's wrong. It doesn't look like Spectacle is correctly normalizing window coordinates in screen detection; seems like a good lead.

**Comment by eczarny** [comment] 2016-02-17 05:11
@dacodekid I pushed a quick fix that may resolve the issue (it's a shot in the dark really but doesn't hurt to try it out). Please download 1.0.3b again and replace the version of 1.0.3b you have been testing with.

**Comment by jkdufair** [comment] 2016-02-17 15:01
Testing on 3 monitors, moving screens repeatedly and rapidly across all monitors with Terminal.app is working correctly on my system. As is snapping to right 1/3,1/2,2/3

**Comment by dacodekid** [comment] 2016-02-17 16:34
@eczarny Works perfect as before ( 1 -> 2 -> 4 -> 3 or 1 <- 3 <- 4 <- 2) on all windows ( iTerm2, Chrome, Atom).

I don't use `Mail` but as someone mentioned another thread, it still has trouble with 1/3.  For me it works as

(on Landscape)
Full -> 1/2 -> 3/4 -> 3/4 -> 3/4

(on Portrait)
Full -> a little wider than 1/2 and stuck.  Plz see comparison image below (Atom sized as 1/2)

![image](https://cloud.githubusercontent.com/assets/10047844/13116355/afa088c4-d569-11e5-86e6-d038dc2a48a6.png)


---

This below issues with `Chrome` (but only in Portrait screen) is actually been there ever since I'm using Spectacle.

Full -> 1/2 -> 3/4 -> 3/4 -> 3/4....

Doesn't bother me, but just want to bring this to your attention.

**Comment by eczarny** [comment] 2016-02-17 16:53
The problem you are seeing with Mail probably has to do with restrictions on its dimensions. See this section of the README for more details:

https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected

**Comment by dacodekid** [comment] 2016-02-17 17:51
@eczarny - Fair.  By far 1.0.3b is working as expected for my use cases. Will keep u posted with my findings. Thx :+1:  Closing this issue.

**Comment by eczarny** [comment] 2016-02-17 21:45
Reopening due to @zhimsel's find in #531.

**Comment by dacodekid** [comment] 2016-02-18 03:46
I couldn't. It works perfectly fine on my setup.

**Comment by zhimsel** [comment] 2016-02-18 03:53
Hm... I wonder what could be the common factor. What terminal are you using?


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net

**Comment by dacodekid** [comment] 2016-02-18 04:02
iTerm2.  I also tried with Chrome & Atom, and they all works fine here.  Not sure what I'm missing.

**Comment by zhimsel** [comment] 2016-02-18 04:14
Strange. I'll try to replicate the issue again tomorrow. Maybe it was a
fluke.


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net

**Comment by zhimsel** [comment] 2016-02-18 18:40
@dacodekid @eczarny I just double checked on 1.0.3b, and it's not a fluke. To clarify, the 1/3 size issue (#531) is fixed in 1.0.3b, but it introduces an issue where I can't move a window from screen B to screen A, only from A->B. Happens on any window, not just a terminal. I'm running a MBP 15" retina below a 2560x1440 monitor (vertically aligned). If it's relevant, the retina display is scaled down as much as it can (the "1920x1200" mode). 

Running OSX 10.10.5.

**Comment by zhimsel** [comment] 2016-02-18 18:41
@eczarny what ref is 1.0.3b built from?

**Comment by dacodekid** [comment] 2016-02-18 23:26
I tried in both home & work (though both are identical setup) without any issues. Only difference from urs is, all mine are 1080p (portrait). Not sure that would make any difference, but since @eczarny able to reproduce yours, assuming you both have similar setup.

**Comment by eczarny** [comment] 2016-02-19 01:54
1.0.3b is built from 9b500d3a08b3e427f0a52bac0c88d4f8b05985af; I forgot to commit my changes. Oops!

**Comment by eczarny** [comment] 2016-02-19 01:55
I was able to reproduce the issue @zhimsel mentions by vertically "stacking" my displays.

**Comment by zhimsel** [comment] 2016-02-19 01:58
Hmm. I thought it might have something to do with the screen arrangement.
Didn't have a chance to test it yet.

--
Zach Himsel
zach@himsel.net
http://zach.himsel.net

**Comment by eczarny** [comment] 2016-02-19 18:31
I made some additional changes to clean up `SpectacleScreenDetector`. In my testing 8bf9360 appears to work properly when I vertically stack my displays. @zhimsel can you confirm the fix?

**Comment by eczarny** [comment] 2016-02-19 18:33
These are the particular changes that appear to have fixed the problem:

https://github.com/eczarny/spectacle/commit/8bf93606bc69482e670b6cf39632e8b80c533b4b#diff-58f5da2b6a29463fdabb4d7961292573

**Comment by dacodekid** [comment] 2016-02-19 18:43
@eczarny , I'm still on the previous build, but if this is what you & @zhimsel, I still couldn't produce your issues though.

![image](https://cloud.githubusercontent.com/assets/10047844/13185287/4c2333a4-d70e-11e5-82de-ddd443f13ec6.png)

Also this

![image](https://cloud.githubusercontent.com/assets/10047844/13185313/6a4b48a8-d70e-11e5-89b4-f2d8cd4ff04c.png)

and this (my original setup) all works well.
![image](https://cloud.githubusercontent.com/assets/10047844/13185324/79f76ad4-d70e-11e5-97dc-5d1e21dec567.png)

If you have already compiled it for testing, I'm happy to test it.

**Comment by zhimsel** [comment] 2016-02-19 20:59
@eczarny 8bf9360 works fine for me, with both issues. 1/3 sizing works, and I can move between both monitors.

**Comment by zhimsel** [comment] 2016-02-19 21:02
@dacodekid for posterity, this is my monitor arrangement
![screen shot 2016-02-19 at 16 02 27](https://cloud.githubusercontent.com/assets/5325723/13188899/3a306748-d722-11e5-932b-41ed051a1d50.png)

**Closed** 2016-02-21 20:40 UTC

**Comment by Summer88** [comment] 2021-09-09 07:14
Similar issue with different version on Debian 11:
```
ii  kde-spectacle                                 20.12.3-1                       amd64        Screenshot capture utility
ii  xserver-xorg-video-nvidia                     460.91.03-1                     amd64        NVIDIA binary Xorg driver
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM107GLM [Quadro M2000M] [10de:13b0] (rev a2)
Linux  5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```
On the first screen position draw by rectangular region is respected when screenshot is taken.
On the second screen position got some random offset instead of the rectangular region selected.
BR
