### ISSUE TITLE
Would be great to moves apps in full screen mode between monitors

### ISSUE THREAD

**Issue by flinge** [eczarny/spectacle#333] opened 2015-02-26 13:52 UTC
This now does not seems to be working on Yosemite
thanks

**Comment by Erowlin** [comment] 2015-02-26 21:09
It works. Just verify the shortcut.

**Comment by flinge** [comment] 2015-02-27 07:18
Does not work in my case.
When I hit the shortcut on an app that is in full screen mode it just makes
app main working window (below the menus and toolbars) black.
Then app does not appear on other display.
I have "Displays have separate spaces" turned on
I use macbook pro with Dell 4K display

On Fri, Feb 27, 2015 at 12:09 AM, Thomas Romera <notifications@github.com>
wrote:

> It works. Just verify the shortcut.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eczarny/spectacle/issues/333#issuecomment-76273844>.
>



-- 
Best regards,
Evstratenko@GMAIL.com

**Comment by minimenchmuncher** [comment] 2015-03-11 12:14
Agreed with @flinge. Shortcut is verified, I see the same black main app window.
The app works perfectly fine in not-fullscreen-mode.
I likewise have "Displays have separate spaces" turned on.
I use a MBP 13" with 2 external HP E231i's

**Comment by eczarny** [comment] 2015-04-10 19:47
Not sure I follow the problem. Can someone provide some clear steps to reproduce?

**Comment by andyearnshaw** [comment] 2015-05-01 09:27
Here's steps to reproduce, assuming that you have more than one display and they are not mirrored.

1. Open an app that supports native full screen (most do).
2. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd> to go full screen.
3. Press <kbd>Ctrl</kbd> + <kbd>⎇</kbd> + <kbd>⌘</kbd> + <kbd>→</kbd> or <kbd>←</kbd> to move to the next display.

You'll see that the window moves and leaves a black backround, but the window isn't really on the other display.  You can move it back, but it doesn't seem to have its original size.

**Comment by minimenchmuncher** [comment] 2015-05-01 12:33
Thanks @andyearnshaw, exactly the problem that I'm having. One Or two things to add here.

I think that the problem may stem from the OS X handling of spaces, in that Spectacle is moving the window, but not moving the space. At least, that's how it seems to me.

Another thing, not sure that it matters, I think that resizing issue only happens if the screen you're moving the window to is *smaller* than the one you're moving from. If you're moving from a small screen to a big screen and back, there seems to be no problem. Same if the two screens you're using are the same size. If you're going through a smaller screen, the window keeps the smaller resolution. You can regain the original resolution if you press <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd> to go to fullscreen using Spectacle, or pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd> twice to exit fullscreen mode and reenter it.

Some screenshots attached from Safari.

Original Screen:
![screen shot 2015-05-01 at 8 24 21 am](https://cloud.githubusercontent.com/assets/3420931/7430074/7fad98f6-efdb-11e4-9f33-d0244245d2f5.png)

Moved one space to the left:
![screen shot 2015-05-01 at 8 31 03 am 3](https://cloud.githubusercontent.com/assets/3420931/7430139/6f6aec54-efdc-11e4-833e-cf73b513d6af.png)
I can click on both tabs here in Safari, both of them blank.

Moved back to the right to original screen:
![screen shot 2015-05-01 at 8 32 22 am 3](https://cloud.githubusercontent.com/assets/3420931/7430149/9d6efda2-efdc-11e4-8c43-b32a07942af2.png)

**Comment by eczarny** [comment] 2015-08-11 20:54
Closing as a duplicate of #296.

**Closed by eczarny** 2015-08-11 20:54 UTC
Labels: investigating
