### ISSUE TITLE
Feature Request: Half-1/4-3/4-Feature for "corners" as well

### ISSUE THREAD

**Issue by Grunerd** [eczarny/spectacle#472] opened 2015-10-02 16:36 UTC
I love how you can resize windows by pressing the hotkey for "left half" multiple times to resize it in a 1/4 and 3/4 manner horizontally (or vertically, when you use the "top half" command, for example)

I wish we could do that for the corners ("upper left" etc.) as well, on a horizontal manner. So that you can have a window that is 1/4 in width and 1/2 in height in the upper left corner. Or 3/4 in width... That would easily allow a broader variety of window-placements.

Example - Before:
I'd like to position Things and Textual side by side on my secondary monitor in that manner. 

![screen shot 2015-10-02 at 18 34 36 2](https://cloud.githubusercontent.com/assets/11262143/10251915/6f22d62c-6934-11e5-97d0-5069efea44cd.png)

After: 

![screen shot 2015-10-02 at 18 35 55 2](https://cloud.githubusercontent.com/assets/11262143/10251929/7fdb8eb4-6934-11e5-9398-ea8c7e16ad6a.png)

Would that be doable?

**Comment by eczarny** [comment] 2015-10-04 20:05
Closing as a duplicate of #465.

**Closed by eczarny** 2015-10-04 20:05 UTC
