### ISSUE TITLE
few pixels space to menu bar after sending window to upper right

### ISSUE THREAD

**Issue by Cathryne** [eczarny/spectacle#243] opened 2014-07-30 20:37 UTC
Maybe related to #182, #168 and/or https://github.com/eczarny/spectacle/issues/217#issuecomment-46095820

- Mac Book Pro 13, early 2011 with OS X 10.9.4
- external monitor in pivot format
- Spectacle 0.8.5

When sending any window to the top right half of either display, it leaves a few pixels space to the menu bar. In the screenshot in the 3rd link above, it looks like the same distance as to the bottom screen edge.

It's not a big problem in the face of the helpfulness of this app generally, but in a terminal, pretty much half of the last line can be covered by a foreground window in the bottom right.

**Comment by ronaldsuwandi** [comment] 2015-04-24 05:00
Yep, the issue is still there with the latest version (0.8.10) - only happens for terminal (iTerm2 / Terminal)

![image](https://cloud.githubusercontent.com/assets/4120788/7243577/00d5d848-e812-11e4-8804-d5276b117e8c.png)

**Comment by eczarny** [comment] 2015-04-25 16:43
@ronaldsuwandi what you are experiencing with iTerm 2 and Terminal windows is expected behavior. To avoid cutting off a row or a column these apps put restrictions on the dimensions of their windows. You can usually see this yourself if you manually change the width or height of a window using the mouse.

Since Spectacle cannot always get these windows to fit in the intended area of the screen exactly it will gradually shrink the window until it does fit. This leads to the gaps you are seeing.

Closing this issue because it appears related to a number of other closed issues.

**Closed by eczarny** 2015-04-25 16:43 UTC
Labels: defect, ★
