### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by leee** [eczarny/spectacle#312] opened 2015-01-29 00:23 UTC
Perhaps my google-fu is not working, but I can't seem to find some sort of configuration file that I can save and deploy across multiple machines for persistent settings.

Is there something like this and I'm just not doing well with searching or is this not an implemented feature?

Thank you!

**Comment by JamshedVesuna** [comment] 2015-01-29 06:49
+1 This would be great to know!

**Comment by andreicek** [comment] 2015-03-15 13:46
+1 I really like the app so far. This would be great!

**Comment by eczarny** [comment] 2015-04-10 17:17
I hope to introduce #45 at some point to make it possible for folks to export/import these settings. Taking things a bit further #345 mentions introducing a preference sync feature as well. In the meantime you may find this to be a helpful workaround:

https://github.com/mathiasbynens/dotfiles/issues/507#issue-59460151

For my own sanity I'm going to close this issue as a duplicate of #45 and #345.

**Closed by eczarny** 2015-04-10 17:17 UTC

**Comment by leee** [comment] 2015-04-10 22:13
@eczarny Merge 345 into 45 and reference the workaround there?

**Comment by eczarny** [comment] 2015-04-11 15:16
#345 and #45 are slightly different. One issue just calls for the ability to export/import settings (though it would allow manually syncing settings). The other would provide actual (potentially iCloud) syncing between computers running Spectacle.

**Comment by pozix604** [comment] 2015-04-16 02:19
+1 for export/import of preferences. If it can be done on the command line so that it can be automated, even better.

**Comment by peterromfeldhk** [comment] 2015-07-10 16:47
+1
