### ISSUE TITLE
Feature request: Allow window movement between internal virtual desktops

### ISSUE THREAD

**Issue by kaustavha** [eczarny/spectacle#703] opened 2016-12-31 03:03 UTC
macOS lets you have several different desktops that can be switched between; single display. 
It'd be nice to be able to toss windows over to the other virtual desktops without having multiple physical displays.

**Comment by eczarny** [comment] 2017-01-10 15:21
Duplicate of #15.

**Closed by eczarny** 2017-01-10 15:21 UTC
