### ISSUE TITLE
Not (always) resizing java application windows

### ISSUE THREAD

**Issue by danielzen** [eczarny/spectacle#517] opened 2016-01-19 16:13 UTC
I am big user of WebStorm, and sometimes it gets into a state where Spectacle stops being able to resize, and instead plays the alert sound instead. I'm guessing that it is because it is a java windows. I would gladly send debug info if instructed how to do so.

Having used both Better Touch Tools & SizeUp, I can attest to that fact that this does not happen with them.

Restarting WebStorm makes Spectacle start working again.

**Comment by dilbert88** [comment] 2016-01-19 19:58
I'm seeing the exact same behavior in Intellij (not surprising given it's relation to WebStorm). It works again if I restart Intellij.

**Comment by rkrauskopf** [comment] 2016-01-20 21:52
I'm seeing the same issue on my copy of WebStorm as well.

**Comment by clevi** [comment] 2016-01-22 13:58
Hi there, I've been seeing this issue with my copy of RubyMine as well. Restarting is also a temporary fix for me, but the problem usually returns after a short while.

**Comment by patkujawa-wf** [comment] 2016-01-27 17:49
I'm experiencing it with PyCharm as well. I don't know if it's just PyCharm 5, which I recently upgraded to. This never used to happen with PyCharm, but I had noticed it happening with Adobe Acrobat (which never seems to work).

**Comment by eczarny** [comment] 2016-02-10 21:19
I believe this is an issue with these IDEs recently moving to a recent JVM. Here is the issue being tracked by JetBrains:

https://youtrack.jetbrains.com/issue/IDEA-149718

Closing this as a duplicate of #500.

**Closed by eczarny** 2016-02-10 21:19 UTC
