### ISSUE TITLE
SPECTACLE 1.0.6 OS X EL CAPITAN - Bug in split screen and full screan command (Alt+CMD+F)

### ISSUE THREAD

**Issue by webmatrixxxl** [eczarny/spectacle#604] opened 2016-05-25 12:07 UTC
The bug is captuered here:
http://quick.as/3ja9UoBaJ

It is loop trying to fit window.

**Comment by eczarny** [comment] 2016-07-15 04:30
Duplicate of #104 (the same applies to split screen windows).

**Closed by eczarny** 2016-07-15 04:30 UTC
