### ISSUE TITLE
Application not working at all after latest release+

### ISSUE THREAD

**Issue by patrickcze** [eczarny/spectacle#660] opened 2016-09-29 01:34 UTC
After updating to version 1.1 I have been unable to get the app to work on my desktop at all. Not sure why?

**Comment by mardlin** [comment] 2016-09-29 16:53
I have the same issue.

**Comment by mardlin** [comment] 2016-09-29 18:28
I'd discovered that the issue is specific to the "alt" key, ie. spectacle doesn't recognize the key at all. This only affects one of my two machines running OS X 10.11.6, but I can't identify the difference between the two which causes the issue.

**Comment by patrickcze** [comment] 2016-09-30 03:52
I have also only seen this on one of my two machines

**Comment by bemky** [comment] 2016-10-04 15:57
I did a clean install of Sierra, and the "alt" key does not work. I don't know if I was on Spectacle 1.1 before wiping and installing so I can't say if it's Sierra or Spectacle 1.1

**Comment by patrickcze** [comment] 2016-10-04 17:26
I can confirm that this issue is occurring only on my El Capitan machine and that my MacBook Pro running Sierra is still functioning.

**Comment by eczarny** [comment] 2016-12-01 16:44
The issue with the option key is being tracked in #657.

As for why Spectacle isn't working in El Capitan I'm unsure. I just recently switched to Sierra and had no trouble before upgrading or after. It's worth noting that I have seen issues in the last on El Capitan where Spectacle would sometimes just stop working. After rebooting things would work again as expected. I've always chalked it up to a bug in OS X.

Closing this for now. If the issue persists feel free to reopen.

**Closed by eczarny** 2016-12-01 16:44 UTC
