### ISSUE TITLE
shortcuts containing number keys: numpad VS number-row

### ISSUE THREAD

**Issue by guillaumesalagnac** [eczarny/spectacle#393] opened 2015-05-18 18:19 UTC
My *Control+Alt+Numbers* shortcuts respond to number keys from the numpad, but not from the main number row. And I can reassign each one to a *Control+Alt+NumberFromRow* shortcut, but then it will not respond to *Control+Alt+NumberFromNumpad* any more. (I hope this makes sense to anyone) 

Is this a feature ? if yes, then I'd love to see both types of keys displayed differently in the preference windows and in the menus. 

or is this a bug ? if yes, i'd love to see this one fixed (so that I can keep my shortcuts on the numpad, and still be able to use Spectacle when I'm on the laptop keyboard only)

**Comment by eczarny** [comment] 2015-06-11 20:05
What happens if you enable num lock?

**Comment by guillaumesalagnac** [comment] 2015-06-12 08:02
Neither my laptop (mid-2014 mbp) nor my external keyboard (classic aluminim usb) have a num-lock key. So I'm not sure to understand your suggestion ; what should I do again ?

**Comment by eczarny** [comment] 2015-08-11 21:20
Got it. It sounds like the keys on the num pad are treated differently than the row of numeric keys. I believe I have a similar keyboard at work so once I'm back in the office I'll try look into this a bit more!

**Comment by eczarny** [comment] 2015-08-16 03:59
Duplicate of #241.

**Closed by eczarny** 2015-08-16 03:59 UTC
Labels: defect, pending, ★★

**Comment by guillaumesalagnac** [comment] 2015-08-31 11:54
well, sorry for the duplicate report. Cheers.
