### ISSUE TITLE
Can't assign shortcut combination Option+xy

### ISSUE THREAD

**Issue by inco8nit** [eczarny/spectacle#688] opened 2016-12-08 21:59 UTC
Hello!

I've been using spectacle for a few years now, and until now I used shortcuts like Option+F for fullscreen and so on. I reseted my Mac and now unfortunately it doesn't let me create this kind of shortcut without adding another key like cmd or shift.

**Comment by Elipasousa** [comment] 2016-12-13 12:01
+1

**Comment by eczarny** [comment] 2016-12-17 17:07
Duplicate of #657.

**Closed by eczarny** 2016-12-17 17:07 UTC
