### ISSUE TITLE
After using Right half there is a gap on the right side on screen sometimes  v2

### ISSUE THREAD

**Issue by Bilalh** [eczarny/spectacle#607] opened 2016-05-27 00:01 UTC
Left half still works correctly when this occurs. This oddity only happens for a short period of time then Right side starts to work correctly again.

Since I could not reopen #554 I created this issue, 

Here is a gif showing that Left half still works correctly and Right half leaving a gap on the right.

Spectacle Version 1.0.6 (593)

OS X 110.11.5 (15F34)
MacBook Pro (Retina, Mid 2012)

This has happened with at lest  Safari.

![out](https://cloud.githubusercontent.com/assets/171602/15593626/104d9ef2-23a6-11e6-80f1-6f5eb35d3f33.gif)

**Comment by trevorstarick** [comment] 2016-05-27 01:40
I've been having the same issue as Bilalh but with Chrome instead of Safari.

**Comment by orhanhenrik** [comment] 2016-05-27 09:15
I've been having this issue too with Chrome (version 50) and slack (version 2). Also a lot of other things that seem weird. Sometimes the fullscreen hotkey (cmd+alt+f) only resizes the window to a slightly larger size. If I press it many times it ends up filling the whole screen.
Also if I go from upper-half and then try right-half (cmd+alt+rightarrow) it fills the left half of the screen.

**Comment by davharris** [comment] 2016-05-29 01:41
I just started noticing this today too, with Chrome and Skype. Mail.app moves correctly, but with a one-second delay.

I'm on version 1.0.6, on a 13" retina MBP, OSX 10.11.5 (15F34)

**Comment by cnandreu** [comment] 2016-05-29 02:31
I've also ran into this bug.

I tried downgrading Spectacle from 1.0.6 to every version down to 1.0.1 (https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.1.zip), but some apps (i.e. Chrome v51, Slack v2) still had the issue. I tried restarting my computer, but no change.

Then I realized I recently installed an app (https://qotoqot.com/qbserve/) that required access to Accessibility (System Preferences > Security & Privacy > Privacy tab). That's the same access that Spectacle needs to move windows around. I un-ticked & closed all apps listed in the Accessibility list, then I closed (cmd+q) and opened Chrome. The problem seems to have gone away. 

Hopefully this may help as workaround or provide additional insight into reproduction steps required to fix this.

For what it's worth, I recorded a short video showing more or less the reproduction steps listed above:
https://youtu.be/nugm_r3GinU

The important bits from the video:
[0:00-0:13] Only Spectacle has Accessibility access. Chrome works fine. I used option+cmd+[left/right arrow] to move the window.
[0:13-0:22] Gave qbserve Accessibility access, but didn't have the app opened. Everything worked fine still.
[0:23-0:41] Shows the bug.

I'm on OSX 10.11.5 (15F34) using a MacBook Pro (Retina, 15-inch, Mid 2015).

**Comment by davharris** [comment] 2016-05-29 03:11
I had recently installed the same app.  Nice catch.

**Comment by ivmirx** [comment] 2016-05-29 03:37
Hi, developer of Qbserve here. Qbserve uses AX API by getting AXUIElementRef appRef = AXUIElementCreateApplication(pid); and then finding nodes that are required for time tracking (once in 3 seconds).

It doesn't change windows sizes or positions, so I think it could be AX internal issue.

Spectacle is not the only app that got into a conflict, there're also issues with Hammerspoon and Moom, both use AX to move windows. (But I was able to fix Moom just by restarting the system.)

I'm a bit overloaded with bug fixes now, so if someone can run Spectacle from sources together with Qbserve and debug the issue it would be great. Or I'll do it next week. Hope the apps will work together eventually.

**Comment by ivmirx** [comment] 2016-05-29 22:23
Ok, I found the line that does it. There's an undocumented attribute `AXEnhancedUserInterface` that is used by VoiceOver to enable screen reading.

I use it too because Chrome, Opera, and Firefox turn on accessibility for their pages (in case of Firefox – for all the UI) only after this attribute is set on them ([Chromium sources](https://chromium.googlesource.com/chromium/src/+/master/content/browser/accessibility/browser_accessibility_state_impl.h)).

Safari always shows accessibility nodes, so I should not force this attribute on it (my bad, fixed).

And it looks like setting `AXEnhancedUserInterface` leads to the size and position issues for Spectacle and other window-controlling apps.

I tried disabling this attribute when Qbserve doesn't need it. But it's a bad idea because at least Chrome [rebuilds all accessibility data for all its tabs](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/accessibility/browser_accessibility_state_impl.cc&sq=package:chromium&dr=C&l=157&rcl=1464535073) each time when this attribute is turned back on.

So I'm thinking of these solutions:

1. in case AX is not completely broken and it's possible to get correct data from it, I can help with fixes for Spectacle, Hammerspoon and other window controlling apps
2. if it's broken then after a bug report to Apple I will add detection of Spectacle and others and prevent the usage of `AXEnhancedUserInterface` on Chromium-based browsers along with these apps. Qbserve could still track them but it will fail to recognize pages when the address bar is not present (videos, full screen with hidden toolbar).

**Comment by ivmirx** [comment] 2016-06-01 21:25
@Bilalh @davharris @cnandreu We released an update today, the issue with window managers should be fixed (Spectacle, Moom, SizeUp, Optimal Layout, BetterTouchTool, Hammerspoon).

Qbserve now detects if any of these apps are present in the workspace and doesn't touch `AXEnhancedUserInterface` (or turns it off in case it was turned on before).

Also Chrome was just updated and there's improved accessibility for full screen videos, so I plan to stop using this attribute completely in future.

**Comment by marcusmoore** [comment] 2016-06-01 21:41
Thanks @ivmirx. I updated Qbserve and it looks like everything is fixed.

**Comment by Bilalh** [comment] 2016-06-06 02:42
@ivmirx  Quitting Observe (1.35) make no different for me using Safari and still causes the error.  So this issue might be unrelated

**Comment by nabam** [comment] 2016-06-10 23:15
I observe the same behavior in congestion with Punto Switcher.

**Comment by eczarny** [comment] 2016-07-24 18:26
Closing this out as it doesn't appear to be an issue with Spectacle.

**Closed by eczarny** 2016-07-24 18:26 UTC
