### ISSUE TITLE
Add margin to windows that have been Spectacled

### ISSUE THREAD

**Issue by iammenasco** [eczarny/spectacle#708] opened 2017-01-12 21:20 UTC
This is a feature request for an option in the preferences to add a small margin between windows.

As an example, currently with multiple windows everything is right next to each other:

<img width="1680" alt="screen shot 2017-01-12 at 2 17 15 pm" src="https://cloud.githubusercontent.com/assets/5480206/21908707/124b7300-d8d2-11e6-850f-a64836b53a8b.png">

This feature request is to add the ability to add a small margin round everything:

<img width="1680" alt="screen shot 2017-01-12 at 2 17 51 pm" src="https://cloud.githubusercontent.com/assets/5480206/21908717/2282e686-d8d2-11e6-83aa-4ef836903aab.png">

**Comment by eczarny** [comment] 2017-01-28 03:11
Duplicate of #67.

**Closed by eczarny** 2017-01-28 03:11 UTC
