### ISSUE TITLE
Hidden Dock - Margin Bug

### ISSUE THREAD

**Issue by omaraboumrad** [eczarny/spectacle#337] opened 2015-03-02 07:49 UTC
When a dock is hidden (Auto hide), any window positioning to the side where the dock was hidden will leave a margin. Screenshot attached (Case: Autohide dock to the left, snap any window to the left/fullscreen) 

To reproduce:

1- Make dock autohide
2- Make any window fullscreen (or snap it to the location of the dock)

OS X Version: 10.10.2
Hardware: Apple Macbook Pro Retina - Late 2013
Spectacle: 0.8.8 (395)
![screen shot 2015-03-02 at 9 48 04 am](https://cloud.githubusercontent.com/assets/71327/6437026/440383fe-c0c1-11e4-89fb-8628539e57f1.png)

**Comment by waynehoover** [comment] 2015-03-04 01:16
I have tried a couple other OS X window managers and they all do the same thing. Also you can't manually make a screen have no margin on the same edge as the dock either.

**Comment by omaraboumrad** [comment] 2015-03-04 07:22
I'm not sure I understand your second statement. Below is a screenshot after manually moving the window to the same edge of the dock.

![screen shot 2015-03-04 at 9 20 53 am](https://cloud.githubusercontent.com/assets/71327/6479558/ca256d14-c24f-11e4-85b6-c5df9b257e00.png)

**Comment by waynehoover** [comment] 2015-03-04 07:39
Yes, I can manually move it to the edge, but I can’t manually resize it to the edge.

**Comment by williamboman** [comment] 2015-03-21 21:46
+1

**Comment by hjdarnel** [comment] 2015-04-04 20:57
+1

**Comment by ygbr** [comment] 2015-04-07 00:08
+1

**Comment by waynehoover** [comment] 2015-04-09 04:31
I have been able to develop a work around for this by using mjolnir. Basically my config moves the window 4px away from the dock resizes the window 4px larger in the x direction then moves the window 4px back towards the edge of the window. If anyone is interested in my mjolnir config let me know and i'll paste a gist or something. 

The only problem with this solution is that there is a noticeable wiggle as this process moves, resizes and then moves the window again back. Also I think now I know why apple decided to do this, I much more often open my dock when I don't mean to now when scrolling manually with the mouse by dragging the scrollbars, as my dock is on the right edge of my screen.

**Comment by eczarny** [comment] 2015-04-10 17:06
Closing as a duplicate of #282. Please feel free to move discussion to that issue.

**Closed by eczarny** 2015-04-10 17:06 UTC
