### ISSUE TITLE
Vertical 1/3, 2/3

### ISSUE THREAD

**Issue by dy-dx** [eczarny/spectacle#208] opened 2014-05-24 19:26 UTC
I love that when you repeat the "Left Half / Right Half" actions, windows resize to 1/3 or 2/3 of the screen width. However, the "Top Half / Bottom Half" actions don't seem to have this functionality, which I really need.

**Comment by caseyyee** [comment] 2015-02-03 00:57
Another vote for 1/3rds.   Especially useful for moving stuff between finder windows!

**Comment by dy-dx** [comment] 2015-04-15 22:52
Fixed by https://github.com/eczarny/spectacle/pull/309.
Thank you @dwayneyuen & @eczarny! Hope this gets released soon.

**Comment by eczarny** [comment] 2015-04-16 02:00
I'm hoping to cut a release this weekend!

**Comment by eczarny** [comment] 2015-04-16 21:05
Reopening because of a regression @janniklorenz pointed out in issue #321.

**Comment by eczarny** [comment] 2015-04-16 23:38
Okay, I believe I have a fix in place (see 3f8ac6941ec5116a6bf47eafdd1ba0e7f7fd1da5). Closing this issue out again.

**Closed by eczarny** 2015-04-16 23:38 UTC
Labels: enhancement, ★★

**Comment by passsy** [comment] 2015-06-17 09:01
Oh just discovered this works. Thanks!
