### ISSUE TITLE
Next Monitor bug with mixed rotated/non-rotated displays

### ISSUE THREAD

**Issue by EntilZha** [eczarny/spectacle#398] opened 2015-06-01 17:34 UTC
I just swapped over to a work setup which is left to right: mac display, rotated 90 degree display, regular display. When I used the next display key, the pattern was to go from: left display, right display, center display (and opposite for previous display). I believe the order should be: left display, center, right.

I am willing to help fix this, but I have no familiarity with the code base.

**Comment by rybesh** [comment] 2015-06-11 12:03
I'm also seeing this bug.

**Comment by paulblyth** [comment] 2015-06-24 08:10
I get the same issue, similar if not the same setup.

MBP 15"/Yosemite - Thunderbolt to HDMI Display rotated 90 degrees - HDMI display

**Comment by johnelm** [comment] 2015-07-08 18:40
Same here.  I have four (sometimes five) displays, two of them rotated, and the screen switching order makes no sense.  Screenie of layout attached.
<img width="74" alt="cursor_and_built-in_retina_display" src="https://cloud.githubusercontent.com/assets/1995285/8578859/850f866a-256e-11e5-9533-e243d612c089.png">

**Comment by eczarny** [comment] 2015-08-01 21:35
This sounds like a duplicate of #298. Unfortunately it's rather hard for Spectacle to actually know what your preferred order of displays is. All it currently tries to do is guarantee some consistency when you move from the next display to previous display (i.e. the same order is always used when moving a window around, but not necessarily the "correct order").

**Closed by eczarny** 2015-08-01 21:35 UTC
