### ISSUE TITLE
Arrow Keys Do The Opposite

### ISSUE THREAD

**Issue by FrankDraws** [eczarny/spectacle#377] opened 2015-04-23 17:48 UTC
I have a MacBook Pro pushing a Thunderbolt and Cinema Display.

The arrow keys (running version 8.6) work the opposite. So hitting left will make the windows move right and vice versa.

If I have 2 screens then it works fine. Wondering if there's anything that can be done for 3 screens.

**Comment by eczarny** [comment] 2015-04-23 19:02
Closing as a duplicate of #298.

**Closed by eczarny** 2015-04-23 19:02 UTC
