### ISSUE TITLE
Skype 1/3 resize in Spectacle version 0.8.9

### ISSUE THREAD

**Issue by pierregermain** [eczarny/spectacle#361] opened 2015-04-17 15:20 UTC
When resizing Sype App to 1/3 of the window using the "Half" shortcuts the Skype Window does not stay in the 1/3 size but get resized to 1/2. In Spectacle 0.8.8 this was working well.

**Comment by eczarny** [comment] 2015-04-17 15:47
I may have a change on master that might help. Are you able to build and run Spectacle to verify?

**Comment by pierregermain** [comment] 2015-04-17 16:24
sorry , I only use Spectacle as a regular user, but maybe if you say me what to do I can help, yes.

**Comment by eczarny** [comment] 2015-04-17 16:56
That's no problem. I'll download Skype and test things out.

**Comment by pierregermain** [comment] 2015-04-17 16:59
thank you eczarny.

**Comment by pierregermain** [comment] 2015-04-17 17:00
I'll be helping out If you need me.

**Comment by eczarny** [comment] 2015-04-17 17:17
Okay, so it looks like Skype might restrict the size of its window. 1/2 and 2/3 should work, but it seems like 1/3 might be too small for some displays. On my larger secondary display I see it mostly work except if I try moving it to the right third.

**Comment by pierregermain** [comment] 2015-04-17 17:37
Thanks for your investigation. Maybe this information can help you: Today when Updating Spectacle from 0.8.8 to 0.8.9 the resize to 1/3 was not working. But when downgrading back Spectacle to 0.8.8 it is working again.

**Comment by tommythorn** [comment] 2015-04-17 18:40
I have the same problem with Terminal. It worked in the previous version.

**Comment by pierregermain** [comment] 2015-04-17 18:55
Are you using multiple screens ? I remember I was using multiple screens.

**Comment by tommythorn** [comment] 2015-04-17 18:56
Yep, one MBP and two attached monitors (via DP) for a total of three.

**Comment by pierregermain** [comment] 2015-04-17 18:58
I am also using Multiple screens. When resizing to 1/3 in the external monitor it gets like overlapped to the internal monitor and then resized to 1/2 to the external monitor.

**Comment by tommythorn** [comment] 2015-04-17 18:59
Ah, interesting.  Terminal 1/3 resize works on the smaller MBP display.  However, Skype doesn't go 1/3 on any display.

**Comment by eczarny** [comment] 2015-04-20 16:20
Any improvement in 0.8.10?

**Comment by tommythorn** [comment] 2015-04-20 16:25
As prompted, I installed 0.8.10 and it fixed my terminal problems.  Skype doesn't like 1/3 on the small display, but works as expected on the large.  Skype behavior isn't actually an issue for me and I don't know if that's a regression over 0.8.8. Thanks for the amazingly fast turn-around!

**Comment by eczarny** [comment] 2015-04-20 16:31
You're welcome! Many folks were reporting issues in 0.8.9 and I wanted to fix them as fast as I could.

Skype working on the larger display confirms my suspicion that it restricts the dimensions of its windows. The fact it didn't work on a larger display before was definitely a regression. Since it sounds like the issue is as fixed as it can be I'm going to go ahead and close out this issue.

**Closed by eczarny** 2015-04-20 16:31 UTC
Labels: investigating
