### ISSUE TITLE
Steam.app Fails to Resize with Spectacle

### ISSUE THREAD

**Issue by JC713** [eczarny/spectacle#407] opened 2015-06-14 14:56 UTC
For some reason, Spectacle is unable to resize Steam.app. Whenever I attempt it, the window shakes and nothing happens. It is basically refusing to resize. Thanks!

**Comment by triple-take** [comment] 2015-06-19 20:22
I also have this problem, it tries to resize but steam locks it in place for some reason.

**Comment by eczarny** [comment] 2015-08-01 21:21
Closing as a duplicate of #378.

**Closed by eczarny** 2015-08-01 21:21 UTC
