### ISSUE TITLE
Alternate keyboard settings not working

### ISSUE THREAD

**Issue by MWildcard** [eczarny/spectacle#76] opened 2012-11-12 04:17 UTC
I nearly always have the "Dvorak – Qwerty ⌘" keyboard setting enabled, which allows me to type in Dvorak (all the vowels on the left side of the home row, all the common consonants on the right side of the home row—google Dvorak if you haven't encountered this before) but still lets me use all the standard shortcuts I am used to.  For example, the "V" key types a "J" when Dvorak is enabled, but with "Dvorak – Qwerty ⌘", typing ⌘ - "V key" will still do "Paste".  (As opposed to just straight up Dvorak layout, wherein I would have to type "⌘ - Period key", since the period key types a "V" in Dvorak.)

Not so with Spectacle.  For example, to enter the shortcut "⌥⌘J" to center a window, I have to type "⌥⌘C", since Spectacle doesn't recognize the "– Qwerty ⌘" aspect of the keyboard layout.  (The "C" key types "J" in standard Dvorak layout.)

I know this is somewhat esoteric, but all other apps deal with this keyboard setting okay, with very few exceptions.  (LibreOffice mostly works with it, with a few quirks; Acrobat Reader is the only major app I've found that flatly refuses to recognize the shortcuts correctly.)

**Comment by eczarny** [comment] 2015-08-13 03:11
Closing as a duplicate of #395.

**Closed by eczarny** 2015-08-13 03:11 UTC
Labels: defect, ★★
