### ISSUE TITLE
Feature suggestion: Margins/spacing

### ISSUE THREAD

**Issue by sccottt** [eczarny/spectacle#743] opened 2017-03-23 19:21 UTC
I would strangle a guy to get optional margins/spacing between windows in one of these Mac window management tools. Window tiling is 1000% more visually appealing and comfortable w/ a little negative space between the windows.

The only application I can find that does this is [Amethyst](https://github.com/ianyh/Amethyst), but it has a completely different "automatic" layout behavior that I can't get on board with. This application does have a perfect preference option, though, illustrating the idea:

<img width="274" alt="screen shot 2017-03-23 at 12 16 06 pm" src="https://cloud.githubusercontent.com/assets/53540/24266155/0a5176fe-0fc3-11e7-8c14-bd8b70718eef.png">

**Comment by caipre** [comment] 2017-04-25 01:48
Dupe of https://github.com/eczarny/spectacle/issues/67

**Closed** 2017-05-24 19:42 UTC

**Comment by sccottt** [comment] 2017-05-24 19:52
@eczarny #67 and all other tickets related to this are closed. Am I missing something? This seems like an obvious and reasonable feature.

**Comment by eczarny** [comment] 2017-05-24 20:09
I originally closed #67 since I had no plans to implement it. Sorry, should have commented on that issue when I closed it in the first place.

**Comment by sccottt** [comment] 2017-05-24 20:17
😭 OK
