### ISSUE TITLE
[Feature Request] Move windows between virtual desktops

### ISSUE THREAD

**Issue by Orologiaio** [eczarny/spectacle#342] opened 2015-03-18 18:02 UTC
Sorry if an issue already exists, but I couldn't find it.
I'd like to be able to move windows from one virtual desktop to the other. Is this possible / can it be implemented?

**Comment by jgonera** [comment] 2015-03-31 17:34
I'd also love to see this.

**Comment by eczarny** [comment] 2015-04-10 16:47
Closing as a duplicate of #15.

**Closed by eczarny** 2015-04-10 16:47 UTC
