### ISSUE TITLE
Unable to size certain apps to 1/3 size after updating to 0.8.9

### ISSUE THREAD

**Issue by vprasanth** [eczarny/spectacle#364] opened 2015-04-17 20:38 UTC
So far iTerm2 and Slack are the apps affected. Please let me know if I can provide more info.

**Comment by eczarny** [comment] 2015-04-17 21:18
I believe there may be a fix for this on master. Any chance you could verify?

**Comment by kratsg** [comment] 2015-04-17 21:55
This is broken for me, especially with multiple monitors.

**Comment by preetampvp** [comment] 2015-04-17 22:59
Just to add Mac terminal to the list of affected apps.

**Comment by vlinder** [comment] 2015-04-18 10:24
I have this problem too. iTerm2 and Spotify seems to have the same problem. What I can tell from testing around a bit is that if the app refuses to be sized to exactly 1/3 it jumps back to the previous width. Also had it with Messages, until I lessened the width of the sidebar. Then the app was able to resize to 1/3 and spectacle also worked again. iTerm2 will only size itself to a multiple of a line or a column. So maybe that is what breaks it.

**Comment by DmitryKuk** [comment] 2015-04-19 18:32
I have some similar problems:
-- unable to size Yandex.Browser window to 1/3 (drops to 2/3),
-- unable to size many apps (including Apple Mail) to 1/3 or 1/2 from 2/3 (in 0.8.9 only, drops to 2/3).

**Comment by maxkw** [comment] 2015-04-19 20:48
Having the same problem with Emacs version 24.4.1 and iTerm2.

**Comment by kokarn** [comment] 2015-04-20 07:09
I can +1 this but also add another weird issue after 0.8.9.

iTerm2 no longer allows me to set it to 1/2 size on one of my monitors.

I have a 3 monitor setup, 2 lightning and one USB. On the first two it works as expected but on the third one, the USB one, as soon as i try to set it to 1/2 it jumps to the main display.

**Comment by mathieug** [comment] 2015-04-20 08:29
Since 0.8.9 I cannot resize to 1/3 iTerm2 (I haven't tried on another application).
I just downgraded to [0.8.8](https://s3.amazonaws.com/spectacle/downloads/Spectacle+0.8.8.zip).

**Comment by elmart** [comment] 2015-04-20 08:38
Terminal.app also affected for me.

**Comment by corinedwards** [comment] 2015-04-20 11:15
I get this with safari on a macbook air at 1440 x 900. 

![spectacle-one-third-safari-issue](https://cloud.githubusercontent.com/assets/1154708/7229010/53b5e1fe-e7a2-11e4-822f-3a2ed00a9a5f.gif)

**Comment by masenf** [comment] 2015-04-20 12:39
I just tried the version on master@847b2f and the 1/3 size issues with Mac OS Terminal.app are no longer present.

Mac OS X 10.9.5

**Comment by eczarny** [comment] 2015-04-20 14:55
Does 0.8.10 fix any of the issues folks are seeing?

**Comment by groksrc** [comment] 2015-04-20 15:25
I had an issue with resizing on my secondary monitor with 0.8.9.  The issue is fixed with 0.8.10. Thanks!

**Comment by srsudar** [comment] 2015-04-20 15:44
I couldn't resize iterm2 to half screen on my secondary monitor with 0.8.9. It kept bouncing back to mostly on the first screen. This is fixed for the most part in 0.8.10. A small gap remains when resizing that I don't see when I resize Chrome, which could be normal (I don't remember what it was like pre 0.8.9, but I don't remember noticing the gap). I'm attaching screenshots just in case. Screenshots are chrome vs iterm2 after resizing to half screen left. Note the gap present on iterm2.
![screen shot 2015-04-20 at 8 42 33 am](https://cloud.githubusercontent.com/assets/6362625/7234038/41281372-e739-11e4-8c5f-565081742da5.png)

![screen shot 2015-04-20 at 8 40 22 am](https://cloud.githubusercontent.com/assets/6362625/7234020/277435fa-e739-11e4-8b0f-45b7392b3372.png)

**Comment by patkujawa-wf** [comment] 2015-04-20 15:49
iterm resizing is mostly fixed in 0.8.10, though there's still a very small gap all around:
![image](https://cloud.githubusercontent.com/assets/6391742/7234192/8c20c73a-e742-11e4-8148-f68c52f3d734.png)

**Comment by eczarny** [comment] 2015-04-20 15:56
The gap is expected. Terminal restricts the dimensions of its windows so Spectacle will do what it can to make the window fit within the requested bounds.

**Comment by srsudar** [comment] 2015-04-20 15:57
In that case it appears solved for me. Thanks!

**Closed** 2015-04-20 16:09 UTC

**Comment by elmart** [comment] 2015-04-20 16:49
Solved, thx!

**Comment by vprasanth** [comment] 2015-04-20 19:40
@eczarny Sorry mate, was at work. Looks like you got it all out, no longer have the issue. Thanks!!
