### ISSUE TITLE
Shortcut for moving a window to a different desktop

### ISSUE THREAD

**Issue by kyrsjo** [eczarny/spectacle#549] opened 2016-03-02 13:34 UTC
Hello,

would it be possible to add a shortcut for moving a window to a different desktop, i.e. move one desktop left/right and drag that window along? It seems that in stock OsX, this is only possible using a combination of keyboard and mouse.

Best regards,
Kyrre

* Spectacle version https://github.com/kyrsjo/spectacle/commit/c5c367791f2d07993798c364c57be6168d50961f
* OsX 10.11.2

**Comment by joshtronic** [comment] 2016-03-16 19:27
There are next and previous display options in the current version that accomplish this - https://www.dropbox.com/s/20lzvzfssmwi4a0/Screenshot%202016-03-16%2015.25.31.png?dl=0

**Comment by chucksense** [comment] 2016-03-16 20:03
That does displays, not desktops (fka "Spaces") on the same display.  Would be useful to be able to send to next/previous desktop too.

**Comment by joshtronic** [comment] 2016-03-16 21:01
oh gotcha, i misunderstood :+1:

**Comment by aprilmay** [comment] 2016-03-18 06:29
+1.
Just discovered Spectacle and that's the first thing i tried, that would be an awesome feature that i miss so much from Linux desktops :)

**Comment by agentgt** [comment] 2016-03-23 18:33
This is the infamous will not fix duplicate of #15 

Its the only reason I stick with SizeUp.

**Comment by eczarny** [comment] 2016-04-16 14:21
I'd love to support this feature but I've never had the time to build it out. Pull requests are more than welcome.

Closing as a duplicate of the infamous issue #15.

**Closed by eczarny** 2016-04-16 14:21 UTC
