### ISSUE TITLE
New version (1.0.2) problems

### ISSUE THREAD

**Issue by gavocanov** [eczarny/spectacle#534] opened 2016-02-15 13:56 UTC
Hi!

As first thnx for the amazing app, can't even think about working on a Mac without it.

It seems to me like the latest version introduced quite a few problems somehow, for ex. I cant resize incrementally (1/4, 2/4, 3/4) iTerm  and MacVim, by reverting to 1.0.1 this seems to work normally, and it seems like only "some" applications suffer from this, ie. I can resize normally Chrome.

Also when I resize the window using ctrl-alt-shift+left/right, left resizes both width and height of the the window while right resizes just width. Idk if this is a feature or bug, but I liked more how the old version worked, ie. resizing only width.

I'm using OSX 10.11.3 if it's relevant, spectacle was updated by in-app update dialog.

**Comment by eczarny** [comment] 2016-02-15 20:09
Closing as a duplicate of #531. This should be fixed once I release Spectacle 1.0.3.

**Closed by eczarny** 2016-02-15 20:09 UTC
