### ISSUE TITLE
Increase/Decrease window size flexibility

### ISSUE THREAD

**Issue by asafpelegcodes** [eczarny/spectacle#374] opened 2015-04-21 15:38 UTC
I thought it would be nice to have a preference where you can change how much the window size increases or decreases each time that you do the shortcut that trigger the shortcuts that increase or decrease the window size.

**Comment by eczarny** [comment] 2015-04-25 16:45
Have you tried using the ⌃⌥⇧→ and ⌃⌥⇧← shortcuts?

**Comment by asafpelegcodes** [comment] 2015-04-27 18:32
Yes, i've been using those and I like that feature but I'd like to be able to customize the amount the window is growing/shrinking when I execute the shortcut.  Currently I have to hit the shortcut about 5-10  times to satisfy what I'm trying to do.

I guess I might be barking up the wrong tree I'm a little new to mac and I really miss the ability to grow & shrink a window how I used to do in an x-windows style way with alt + mouse right click.  

Since I couldn't find that feature for Mac OS and I was already using spectacle I was hoping it could let me quickly grow & shrink windows.

**Comment by eczarny** [comment] 2015-08-13 23:47
Duplicate of #114.

**Closed by eczarny** 2015-08-13 23:47 UTC
Labels: enhancement, ★
