### ISSUE TITLE
Disable Spectacle in full screen mode

### ISSUE THREAD

**Issue by sdaniel55** [eczarny/spectacle#511] opened 2016-01-12 15:43 UTC
When you use an app in full screen, it shouldn't resize the window, because it's useless.

**Comment by joshtronic** [comment] 2016-01-20 01:15
Actually comes in super handy when you are using the split view in el cap

**Comment by eczarny** [comment] 2016-02-10 21:20
Closing as a duplicate of #468.

**Closed by eczarny** 2016-02-10 21:20 UTC
