### ISSUE TITLE
Safari windows behave strangely in El Capitan

### ISSUE THREAD

**Issue by sejmann** [eczarny/spectacle#446] opened 2015-09-01 00:29 UTC
When sent to left or right in El Capitan beta 5 (15A262e), windows incompletely slide and resize, not quite making it to the edges initially.  If I reissue the hotkey repeatedly, they will eventually end up in the correct location after about 10 attempts, at least when going to the left -- when going to the right, they never quite make it.  Windows of other applications behave properly, that is, they instantly jump to the proper edge and size, as Safari did in Yosemite, but now Safari windows have an animated partial slide/resize in 10.11 beta 5.  My machine is an early 2009 MBP 17.  Here's a double-speed animated gif depicting my attempt to move windows first to the left, and then to the right.

![safari10 11](https://cloud.githubusercontent.com/assets/1660933/9593580/1bc910ba-5005-11e5-87ec-9a4a502a5279.gif)

**Comment by sejmann** [comment] 2015-09-01 18:03
This issue seems to be resolved in El Capitan Public Beta 6 (15A278b), at least on my machine, so you can close it, as far as I'm concerned.  Thanks!

**Comment by sejmann** [comment] 2015-09-11 19:12
I spoke too soon.  This abnormal behavior still exists in the El Capitan GM -- but only after Safari is open for some hours.  Once present, the issue can be temporarily ameliorated by closing and reopening Safari.  It will return, however.

**Comment by eczarny** [comment] 2015-09-11 23:45
We can reopen after release if the issues continues to exist.

**Comment by sejmann** [comment] 2015-09-14 08:25
Not sure if you meant after the recent 1.0.1 Spectacle release, or if you meant after the Sept 30 El Capitan release -- but I will say the issue persists in the 1.0.1 version of Spectacle, still running on El Cap GM.  I have also noticed that the same behavior also affects Mail.  Not sure what those two apps have in common.  Restarting Spectacle has no affect.  Restarting the affected window's app seems to temporarily correct the problem.  I'm not sure if the OS is just misreporting window position and size stats after a while, or misfiring on any repositioning, but I would happily collect some diagnostics if you'd like to suggest any.

**Comment by sejmann** [comment] 2015-10-03 02:28
This issue remains a problem in El Capitan 10.11 final, and even the public beta for 10.11.1.  Perhaps you might consider reopening this issue.  It still manifests in exactly the same way as in the animated gif accompaying my initial post.  It affects Safari, but not initially -- only after several hours.  This is extremely reproducable.  Quitting and restarting Safari temporarily fixes the problem, until it returns a few hours later.  I can't imagine what could be changing.  I think I'll try some other window management apps and see if they're also similarly affected, and report back.

**Comment by hoosierEE** [comment] 2015-10-05 14:02
El Capitan includes some window-tiling type features (called [Split View](http://www.cio.com/article/2972683/os-x/os-x-el-capitan-use-split-view-window-resizing.html)) which might be conflicting with Spectacle.  I'm using Spectacle 1.0.1 currently and will upgrade from Yosemite to El Capitan this morning.  We'll see how it goes.

**Comment by sejmann** [comment] 2016-01-28 12:02
By the way, this is still happening to me in 10.11.3.  Have you yet experienced it @hoosierEE ?

**Comment by joedaniels29** [comment] 2016-02-16 15:49
+1 Happening to me! Let me know if theres any info I can give that might be of use!

Whats weird is that it only sometimes happens.

**Comment by eczarny** [comment] 2016-05-05 03:31
Closing as this problem has been reported as intermittent, the issue hasn't had an update in a while, and I'm unable to reproduce in 10.11.4.

**Closed by eczarny** 2016-05-05 03:31 UTC
Labels: investigating

**Comment by sdrygalski** [comment] 2016-05-27 12:53
I got it too...

**Comment by sdrygalski** [comment] 2016-05-27 13:00
In one evening I installed BetterTouchTool and Stay - everything works. Next morning updated osx to 10.11.15 and it broke up.

**Comment by joedaniels29** [comment] 2016-05-27 13:08
Yeah, I still get this quite regularly, though I anticipate this is something internal to safari's rendering, and not something that can be addressed through the accessibility api.

**Comment by sdrygalski** [comment] 2016-05-27 13:25
After update I got in in other apps too.....

**Comment by robertmilner** [comment] 2016-08-02 20:34
I have had it for several months, since El Capitan. I feel like it has worked with Safari and then it doesn't. After reading the other reporters posts I will see if I can identify a timeout issue or some other event now that I know I'm not crazy! I would also place blame on the Mac Split View feature.

**Comment by nodakjones** [comment] 2017-03-20 20:36
I'm pretty sure this is still an issue on El Capitan and Safari.  Works great for awhile and then Spectacle shortcut keys stops working. If I click on Spectacle and then click on a command that will work.  If I close Spectacle and re-open then the shortcuts will work again.

**Comment by dylan-chong** [comment] 2019-01-29 00:57
This issue has happened to me for the past few weeks on Mac OS  10.3.6, I'm not sure when it started happening as I did not do any major updates around the time that this problem started.

 rebooting my computer seemed to make the problem go away but it will eventually come back within a few hours roughly

 note: this problem happens with all windows, not just Safari

 did anyone find any solution?

**Comment by dylan-chong** [comment] 2019-02-04 01:45
@eczarny Looks like this issue has been abandoned. I can replicate this issue (more or less) as described in my comment above, is there anything i can do to help debug this issue ?

**Comment by dylan-chong** [comment] 2019-03-26 04:09
`defaults write -g NSWindowResizeTime -float 0.0001`

This seems to fix it, at least for the meantime. I'll report back with how it goes 

http://osxdaily.com/2015/01/06/make-the-window-resizing-animation-speed-instant-in-mac-os-x/
