### ISSUE TITLE
Undo action not working

### ISSUE THREAD

**Issue by themightyoarfish** [eczarny/spectacle#588] opened 2016-05-04 18:24 UTC
This problem happens with any app in version 1.0.6 for me. Hitting `cmd-alt-Y` (or manually selecting the menu item) rings the error bell. Console shows no log output. 

Update: Now sometimes it works, but only one step back, most of the time, nothing. I see no regularity to this, except that when it fails once, it will continue to fail at least until I use a different action which then sometimes but not always can be undone.

**Comment by matteck** [comment] 2016-05-24 06:49
I'm seeing the same behavior, where undo mostly doesn't work but sometimes works one step, but only with Firefox

Other apps I've tried that work: Messages, Calendar, Finder, Atom, Telegram, Airmail, Spotify

**Comment by matteck** [comment] 2016-05-27 01:24
Using a different computer, undo is working normally with Firefox.

So far I have only seen this issue on one computer, and only with Firefox, but it is happening consistently there.

**Comment by matteck** [comment] 2016-06-02 02:26
It's no longer happening on the original computer. I can't reproduce it at all now.

**Comment by EstiT** [comment] 2016-08-21 23:11
Command Z doesn't work for me at all when Spectacle is running

**Comment by themightyoarfish** [comment] 2016-08-21 23:50
You mean Command-Y, right?

**Comment by EstiT** [comment] 2016-08-22 01:33
Nope. The undo shortcut

**Comment by themightyoarfish** [comment] 2016-08-22 05:51
The undo shortcut for spectacle is cmd-y. Or do you mean that undo in other apps does not work when spectacle is active? These are separate issues.

**Comment by EstiT** [comment] 2016-08-22 05:53
The undo in other apps when spectacle is active.

**Comment by eczarny** [comment] 2016-08-27 03:37
@EstiT Is the undo shortcut and one of Spectacle's shortcuts colliding? Have you checked Spectacle's preferences?

**Comment by EstiT** [comment] 2016-08-27 03:53
When undo is set to command Z in Spectacle, it doesn't work elsewhere. I just had to delete that default shortcut. I had checked the preferences many times before but I didn't realize that it was not universal.  
<img width="60%" alt="screen shot 2016-08-26 at 11 47 13 pm" src="https://cloud.githubusercontent.com/assets/17136826/18024979/146fd0ce-6be8-11e6-8088-6cd6dd7745b5.png">

**Comment by themightyoarfish** [comment] 2016-08-27 09:11
For me, the default was always Cmd-Y.

**Comment by eczarny** [comment] 2016-08-27 14:22
@EstiT that's likely the reason. If you use a different shortcut for Spectacle's undo action it should work.

**Comment by eczarny** [comment] 2016-08-27 14:41
@themightyoarfish are you still seeing problems? I think I've ran into similar issues before with undoing or redoing a window action. I'll investigate a bit more today.

**Comment by themightyoarfish** [comment] 2016-08-27 14:50
No it's back to working for me currently.

**Comment by eczarny** [comment] 2016-08-27 14:52
Gotcha. I'll close this out in the meantime but please reopen of you run into more trouble.

**Closed by eczarny** 2016-08-27 14:52 UTC
Labels: investigating
