### ISSUE TITLE
Some windows get stuck on one display

### ISSUE THREAD

**Issue by kevinjamescasey** [eczarny/spectacle#579] opened 2016-05-03 13:57 UTC
Before the update to 1.0.5 I never saw a problem but now for some windows the Next Display and Previous Display actions don't work. The window will flash on the next or previous display for a fraction of a second but immediately go back to where they were.  I'm using OS X El Capitan 10.11.4

**Comment by eczarny** [comment] 2016-05-03 14:19
@kevinjamescasey What is your display setup? Is at least one display much larger than the others?

**Comment by eczarny** [comment] 2016-05-03 14:22
Closing this as a duplicate of #575.

**Closed by eczarny** 2016-05-03 14:22 UTC
Labels: investigating
