### ISSUE TITLE
Feature suggestion: Quick key fires a pre-defined height and width of the active window

### ISSUE THREAD

**Issue by rologica** [eczarny/spectacle#672] opened 2016-10-31 10:09 UTC
It would be a great addition to have the possibility to set the height and width of the active window to a pre-defined value. For instance: with the quick key ctrl+alt+command+D the active window is set to 1280 x 800. The pre-defined values should be set via the preferences.

**Comment by eczarny** [comment] 2016-12-01 17:01
Duplicate of #610.

**Closed by eczarny** 2016-12-01 17:01 UTC
