### ISSUE TITLE
iTerm2 not working with Spectacle

### ISSUE THREAD

**Issue by gnachman** [eczarny/spectacle#661] opened 2016-09-29 04:00 UTC
Hi, I'm the iTerm2 developer. I received this bug report about iTerm2 and Spectacle:

https://gitlab.com/gnachman/iterm2/issues/5173

For some reason (for this user, at least) the OS routes keyboard shortcuts to iTerm2 instead of to Spectacle. I can't see why this would be, but maybe Spectacle is doing something I don't understand. Happy to help investigate this with you.

**Comment by lamarqua** [comment] 2016-09-29 11:00
This is the issue I had previously opened: https://github.com/eczarny/spectacle/issues/640

**Comment by eczarny** [comment] 2016-12-01 16:48
@gnachman sorry, only getting around to this now. Is Spectacle the only app that runs into trouble with iTerm 2? I'm not really sure what would be happening but perhaps there's some subtle issue with the way Spectacle registers its global shortcuts?

For the curious this is how Spectacle registers its shortcuts:

https://github.com/eczarny/spectacle/blob/master/Spectacle/Sources/SpectacleShortcutManager.m#L169-L189

**Comment by gnachman** [comment] 2016-12-05 06:01
I'm not aware of other apps that have issues with carbon hotkeys with iTerm2.

When I register for hotkeys, I use `GetEventDispatcherTarget()` instead of `GetApplicationEventTarget()`, but other than that it seems fine. I have no idea if this would be responsible for the issue, or if I should actually change my code instead :).

Another possibility is that something went wrong in your hotkey handler. Maybe there's some way @lamarqua  can see if this code path is taken:

https://github.com/eczarny/spectacle/blob/master/Spectacle/Sources/SpectacleShortcutManager.m#L218

Depending on `err` it might allow the key to get sent to other apps.

**Comment by lamarqua** [comment] 2016-12-08 22:47
Argh. So, I was tired of dealing with this, so I went the nuclear option and removed both apps + all remaining config files before reinstalling them both. After that it worked. (I figured something must have been wrong with my machine if I was the only one having that problem.)
One thing I noticed, which may have been an issue: I actually had two copies of Spectacle, one in `/Applications` and one in `~/Applications`. Dunno if it was my fault or not (one of them was installed by `brew cask`). So, heh problem solved, yay! But why, we won't know... 
I still have the config files that I nuked somewhere on Time Machine, if you're very interested in fixing that bug.

**Comment by eczarny** [comment] 2016-12-17 19:47
Given @lamarqua was able to resolve the issue by reinstalling both apps I'm not quite sure what to make of this issue.

@gnachman you raise a good point about that code. Though my understanding is if that event handler doesn't handle the event it should be forwarded to the next installed handler. It's a bit hard to actually figure out how you're supposed to use that API though so I may be mistaken.

**Comment by SpaceK33z** [comment] 2016-12-18 20:57
I use iTerm2 and Spectacle every day, and it works fine for me (not sure if this adds anything, but just in case).

**Comment by gnachman** [comment] 2016-12-20 20:41
Fine with me if you want to close this out until we get a reproducible case.

**Comment by eczarny** [comment] 2016-12-22 14:33
Closing this for now. Let's please reopen if the issue returns and we can reproduce.

**Closed by eczarny** 2016-12-22 14:33 UTC
Labels: defect, ★★

**Comment by hankjacobs** [comment] 2017-02-08 21:03
I'm seeing the same issue and uninstalling/reinstalling both applications hasn't resolved it. Interestingly, [shiftit](https://github.com/fikovnik/ShiftIt) works. I've tried to change spectacle to use the key combinations shiftit uses but still no luck.

**Comment by Neirda24** [comment] 2019-01-17 09:22
Hi I'm having the issue myself. I just reinstalled my macbook. Before it was working well. But since it seems like spectacle it taking the lead on listening my shortcut keys. I use iterm in fullscreen always. I'd like (when I split panels) to be able to move from one panel to another. The shortcut is `cmd` + `option` + `arrow key`. Clearly when I disable Spectacle it works just fine... Can I disable spectacle for one app ? Or having Spectacle being the latest listener (as a fallback in the current app does not support the shortcut). Or maybe disable Spectacle when used in fullscreen app ?

**Comment by jackkinsella** [comment] 2019-04-12 13:42
Started having this issue recently. Tried nuking both applications and settings, but no luck. When I type in "cmd-option-leftarrow" into iterm2 running bash, I hear an alarm and see the characters ";9D". The iterm debug log is attached.

[debuglog.txt](https://github.com/eczarny/spectacle/files/3073501/debuglog.txt)
