### ISSUE TITLE
Spectacle misplaces windows on secondary display when used with LG 5K monitor

### ISSUE THREAD

**Issue by mshaler** [eczarny/spectacle#726] opened 2017-02-08 15:39 UTC
Configuration: LG UltraFine5K is primary display and Built-in Retina Display is secondary.  When trying to place a given window into upper right corner of secondary display, that window moves partially to primary display.  This issue does not occur when using the laptop standalone.  Any recommendations?

**Comment by eczarny** [comment] 2017-02-25 21:09
Closing as a duplicate of #576.

**Closed by eczarny** 2017-02-25 21:09 UTC
