### ISSUE TITLE
Doesn't Work With Any Adobe CC Apps

### ISSUE THREAD

**Issue by Undistraction** [eczarny/spectacle#675] opened 2016-11-02 16:35 UTC
Issues when used with Photoshop, Illustrator or Lightroom.

With Illustrator the Window momentarily resizes, but returns to its original size.

With Photoshop nothing happens as all.  

With Lightroom the window resizes, but not to the correct dimensions (for example when set to the upper half of the screen the window is resized to the upper 2/3rds).

**Comment by marlonrichert** [comment] 2016-11-04 11:41
Duplicate of #641

**Closed** 2016-12-01 16:34 UTC
