### ISSUE TITLE
4px gap between edge of the screen and frame where the Dock is located. 

### ISSUE THREAD

**Issue by mvaneijgen** [eczarny/spectacle#344] opened 2015-03-25 10:33 UTC
Is there a way to remove this 4px gap 
![alt text](http://i.imgur.com/eIb07a4.jpg) 
It is only where the dock is located.

**Comment by ygbr** [comment] 2015-04-07 00:08
+1

**Comment by eczarny** [comment] 2015-04-10 16:45
Closing as a duplicate of #282.

**Comment by mvaneijgen** [comment] 2015-04-10 16:46
@eczarny could you link to to duplicate?

**Closed by eczarny** 2015-04-10 16:45 UTC
