### ISSUE TITLE
Incorrect Positioning Using Shortcuts After Unplugging External Monitor

### ISSUE THREAD

**Issue by gneatgeek** [eczarny/spectacle#727] opened 2017-02-10 03:43 UTC
## Description of the Issue
The following shortcuts place the window underneath the doc once I unplug the external monitor:
- Center
- Fullscreen
- Left Half
- Right Half
- Lower Left
- Lower Right

I have not tested the other shortcuts out.  The issue does seem to resolve itself after issuing a few of the commands; it resolved after I took screenshots.

### Screenshots
<img src="https://cloud.githubusercontent.com/assets/1232730/22813209/d41ad240-eefe-11e6-853e-683a677c19b8.jpg" alt="left_large_shortcut" width="200"> <img src="https://cloud.githubusercontent.com/assets/1232730/22813213/d79eafa4-eefe-11e6-93c6-28e1fc289e19.jpg" alt="right_half_shortcut" width="200"> <img src="https://cloud.githubusercontent.com/assets/1232730/22813216/dbe1b2dc-eefe-11e6-88fb-a5f6b8b69efb.jpg" alt="fullscreen_shortcut" width="200">

### Related Issues
I believe that this may be related to #726, #709, & #700.

## System Setup
- MacOS Sierra 10.12.3
- Dell 34" external monitor
- Spectacle 1.2 (672)

I use the external monitor as my primary display when it is connected. This issue only seems to occur when I unplug the external monitor.

**Comment by eczarny** [comment] 2017-02-25 21:10
@gneatgeek is this a 4K display?

**Comment by eczarny** [comment] 2017-02-25 21:11
This sounds like a duplicate of #576. I want to confirm though.

**Comment by gneatgeek** [comment] 2017-03-04 04:43
Sorry for the delay. Yes, it's a 4K screen.

**Comment by eczarny** [comment] 2017-05-24 19:48
Closing in favor of #576.

**Closed by eczarny** 2017-05-24 19:48 UTC
Labels: investigating
