### ISSUE TITLE
Doesn't Work w/ QT5 Apps

### ISSUE THREAD

**Issue by tablador** [eczarny/spectacle#529] opened 2016-02-11 00:17 UTC
For some reason, apps built with QT5 don't respond to the window resizing commands issued by Spectacle. It seems like this is an issue that might need resolving between Spectacle and QT5 devs--I'm guessing there is something the QT framework needs to support that was somehow dropped in the move to 5.x.

**Comment by tablador** [comment] 2016-02-11 00:56
Is it possible this is because QT5 doesn't implement the acessability protocol?

**Comment by eczarny** [comment] 2016-02-12 00:16
That is very likely the reason.

**Comment by tablador** [comment] 2016-02-12 22:34
I'd like to help push this to get fixed--can you describe what functions in the API you rely upon specifically and I will create a bug with QT5.

**Comment by eczarny** [comment] 2016-02-13 02:34
I actually don't know what work is involved. Spectacle completely relies on system APIs that were designed to work with Cocoa apps. I'm not sure what would need to be done to support these APIs in QT. That's a question for their development team.

**Comment by eczarny** [comment] 2016-02-13 02:35
Closing this issue since there really isn't anything that I can do in Spectacle to fix the issue.

**Closed by eczarny** 2016-02-13 02:35 UTC

**Comment by eczarny** [comment] 2016-02-13 02:39
@tablador if you're able to provide some additional information I may be able to get more of any idea what's going on. Any log messages in Console could be helpful. You can also use the Accessibility Inspector to see if the Qt 5 apps interact with it appropriately.

I'm more than happy to reopen this issue if we can find some concrete issues in Spectacle.

**Comment by tablador** [comment] 2016-02-13 02:47
From Console:

2/12/16 9:44:58.495 PM Spectacle[12279]: Unable to obtain the accessibility element with the specified attribute: AXFocusedApplication (error code -25212)
2/12/16 9:44:58.495 PM Spectacle[12279]: Failed to find the application that currently has focus.

**Comment by eczarny** [comment] 2016-02-13 02:59
Using Accessibility Inspector can you see any helpful information about the windows of the application? What applications reproduce the issue?

**Comment by tablador** [comment] 2016-02-13 12:46
Hrm.. working on this one. I'm on a borrowed computer at the moment--The OS was Yosemite, and Xcode wasn't installed. After upgrading, things seem to be working...so now I am kinda waiting for my old computer to get back (today I think) so i can see what might be going on. Both computers exhibited this behavior, so I'm a bit puzzled until I dig in a bit more. I suppose the good news is that it seems to work. I think there is a possibility that some newer version of Qt might have fixed this, and possibly only fixed it for El Capitan. I'll update to let you know if I find anything, or have further questions to help investigate.

**Comment by tablador** [comment] 2016-02-13 17:36
Just wanted to follow up. Got my computer back, and it looks like this problem has been very recently resolved on both systems. Sorry for the trouble.

**Comment by eczarny** [comment] 2016-02-13 17:48
Not a problem! Thanks for reporting the issue and following up with a detailed investigation. I appreciate the help.
