### ISSUE TITLE
Next Display doesn't use Mac OS X arrangement correctly

### ISSUE THREAD

**Issue by stevebissett** [eczarny/spectacle#496] opened 2015-12-07 09:28 UTC
My current setup:

MacBook Pro (Retina, 15-inch, Mid 2014), with three displays:
Built-in Retina Display
Dell U2412M Display
Dell P2414H Display

OS X Yosemite 10.10.5 (14F27)
I'm using Spectacle Version 1.0.1 (509)

When I use the shortcut keys for `Next Display` or `Previous Display`, it regards the next display as the one on the left. 

Is this intuitive, as we generally read from left to right, so I would consider the next display to be the one on the right?

**Comment by stevebissett** [comment] 2015-12-07 09:28
In other words, if I use the `->` array key, the window moves to the left.

**Comment by esetnik** [comment] 2015-12-09 14:41
+1 i'll investigate and see if I can fix it

**Comment by eczarny** [comment] 2016-01-09 18:24
This has been a long term issue that I haven't been able to invest much time into. It turns out that trying to understand what the "next" display is can bit difficult. The best I've been able to do is at least try and make sure the order remains consistent.

**Comment by eczarny** [comment] 2016-01-09 18:26
I'm closing this as a duplicate of #298 and I'll reopen that issue. I would love to sort this out.

**Closed by eczarny** 2016-01-09 18:26 UTC
